import json
import os
import glob
import re

# Load JSON datasets
items = json.load(open('Assets/StreamingAssets/Data/items.json', 'r', encoding='utf-8'))
recipes = json.load(open('Assets/StreamingAssets/Data/recipes.json', 'r', encoding='utf-8'))
survivors = json.load(open('Assets/StreamingAssets/Data/survivors.json', 'r', encoding='utf-8'))
events = json.load(open('Assets/StreamingAssets/Data/events.json', 'r', encoding='utf-8'))
echoes = json.load(open('Assets/StreamingAssets/Data/echoes.json', 'r', encoding='utf-8'))
radio = json.load(open('Assets/StreamingAssets/Data/radio.json', 'r', encoding='utf-8'))
locations = json.load(open('Assets/StreamingAssets/Data/locations.json', 'r', encoding='utf-8'))

# Load IntelBible text
with open('IntelBible.md', 'r', encoding='utf-8') as f:
    intel_bible_text = f.read()

# Load README text
with open('README.md', 'r', encoding='utf-8') as f:
    readme_text = f.read()

# Scan C# files
game_dir = 'Assets/_Game'
cs_files = glob.glob(os.path.join(game_dir, '**/*.cs'), recursive=True)

by_folder = {}
for path in cs_files:
    rel = os.path.relpath(path, game_dir)
    folder = rel.split(os.sep)[0]
    by_folder.setdefault(folder, []).append(path)

output_lines = []

def p(text=""):
    output_lines.append(text)

p("# ASHFALL (Working Title: Atomic War - Starving Survival)")
p("## COMPREHENSIVE GAME DESIGN, CODEBASE ARCHITECTURE & MASTER REFERENCE MANUAL")
p("> **Document Purpose:** This master reference document provides a complete, exhaustive, 360-degree blueprint of *ASHFALL*. It contains the full lore bible, system architecture, data models, mechanics, UI structure, current progress, and raw authored catalogs (321 items, 72 survivors, 16 recipes, 39 events, 15 echoes, 50 radio broadcasts, 5 locations). Use this text file directly in LLM chats (Qwen, Gemini, ChatGPT, Claude, Perplexity, Vibe Le Chat) for deep-dive brainstorming, feature expansion, narrative writing, and balance tuning.")
p()
p("---")
p()
p("## SYSTEM PROMPT & LLM INSTRUCTION HEADER")
p("```")
p("YOU ARE AN AI SYSTEM ARCHITECT AND LEAD GAME DESIGNER REVIEWING THE 'ASHFALL' SURVIVAL GAME MASTER DOCUMENT.")
p("Context: ASHFALL is an original 2D atomic-war survival management game built in Unity 6 LTS (URP 2D, C#, UI Toolkit, ScriptableObjects + JSON, Utility AI).")
p("Tone: Cold, exhausted, human, restrained. Inspired by This War of Mine, Darkest Dungeon, and Frostpunk. No magic, no fantasy, no real-world modern political references.")
p("When generating ideas based on this document:")
p("1. Respect all snake_case ID conventions and data schemas defined herein.")
p("2. Align with the thin-MonoBehaviour / decoupled C# systems architecture.")
p("3. Focus on systemic depth (radiation dosage, shelter degradation, medical pathologies, psychological decay, dynamic economy).")
p("```")
p()
p("---")
p()
p("## CHAPTER 1: EXECUTIVE SUMMARY & GAME VISION")
p()
p("### 1.1 Core Pitch")
p("*ASHFALL* is a hard-grit 2D atomic-war survival management simulation. The player assumes command of an underground fallout shelter (a former pre-war military sub-pen / civil defense bunker) in the upland market town of Tessarat following a catastrophic nuclear exchange between warring regional factions.")
p("Unlike high-power post-apocalyptic power fantasies, *ASHFALL* is defined by scarcity, degradation, sickness, and moral erosion. Survivors are not action heroes; they are traumatized civilians, deserting soldiers, and exhausted specialists fighting against hunger, hypothermia, acute radiation sickness, air filtration failure, and structural collapses.")
p()
p("### 1.2 Aesthetic & Tone Guidelines")
p("- **Visual Style:** 2D gritty graphic-novel aesthetic inspired by *This War of Mine* and *Darkest Dungeon*. Deep chiaroscuro light and shadow, desaturated palette dominated by cold ash blues, charcoal grays, rust oranges, and muted mud browns.")
p("- **Tone:** Cold, exhausted, human, restrained. No heroic monologues or romanticized apocalypse. The tragedy is administrative, physical, and immediate.")
p("- **Realism Guardrails:** Strict grounding in realistic post-nuclear physics and biology. Dosimeters click, iodine protects only the thyroid, blood types must match for transfusions, filters clog with ash, and cold is relentless. Zero fantasy, zero magic, zero aliens, zero sci-fi mutants with lasers.")
p()
p("### 1.3 High-Level Gameplay Loop")
p("1. **Shelter Maintenance & Day Operations:** Manage power grids, air filtration units, water purification, heating fuel, room cleanliness, and structural integrity.")
p("2. **Survivor Need Management:** Allocate rations, clean water, medical treatments, sleep shifts, and psychological support (or discipline) to keep survivors operational.")
p("3. **Intel & Radio Interception:** Tune shortwave and VHF radio bands to gather plume reports, mortar warnings, trade convoy routes, and numbers station coordinates.")
p("4. **Surface Scavenging Expeditions:** Dispatch survivors into irradiated zones (hospitals, gas stations, government bunkers, ruined suburbs) to loot vital components and medicine.")
p("5. **Crisis & Narrative Event Resolution:** Face moral dilemmas, hatch raids, refugee arrivals, internal mutinies, mental breakdowns, and environmental disasters.")
p("6. **Faction Relations & Victory Path Pursuit:** Build alliances or defend against factions (Central Garrison Remnants, Upland Militia, Cultists of the Glow, Warlords) to achieve one of 8 distinct endgame survival conditions.")
p()
p("---")
p()
p("## CHAPTER 2: NARRATIVE BIBLE & WORLD-BUILDING")
p()
p("### 2.1 Pre-War Context & The Fracture")
p("For thirty years, a central government situated in the fertile river valley controlled trade routes, fuel pipelines, iodine stockpiles, and state broadcast networks. The upland provinces provided agricultural yields and raw materials, receiving subsidized grain and infrastructure in return.")
p("When consecutive droughts dried the river system, mutual suspicion erupted into open conflict. The upland provincial assembly voted to withhold grain; the central garrison deployed armor and heavy artillery. The conflict escalated into ridgeline artillery duels, drone strikes on fuel depots, and grinding infantry attrition.")
p()
p("### 2.2 The Exchange & Timeline")
p("- **Days -30 to 0 (Pre-War Escalation):** Propaganda broadcasts mask the collapsing diplomatic cables. Civil defense notices instruct citizens to test iodine pills and locate district fallout shelters.")
p("- **Day 0 (The Exchange):** Detonations occur along strategic targets. An EMP blast disables unshielded electronics. High-altitude ash plumes enter the upper atmosphere.")
p("- **Days 1 to 30 (Panic & Emergency Phase):** Chaos reigns on civilian radio bands. Heavy fallout rain settles over Tessarat. Counter-battery artillery fades into silence as military command structures collapse. Emergency ration centers run dry.")
p("- **Day 30+ (Nuclear Winter & Silent Decay):** Automated emergency loops repeat corrupted instructions. Numbers stations broadcast single-use pad numbers. Temperatures plunge to -15°C to -30°C. Fallout storm fronts sweep the map. Survivors face chronic radiation and resource starvation.")
p()
p("### 2.3 Factions of the Wasteland")
p("1. **Central Garrison Remnants:** Disciplined, heavily armed military survivors maintaining authoritarian protocol. They command tactical gear, fuel, and heavy weapons, but face desertion and logistics collapses.")
p("2. **Upland Provincial Militia:** Local agrarian defense networks fighting for regional autonomy. They possess strong local knowledge, hunting gear, and hidden grain caches, but lack medical supplies.")
p("3. **Cultists of the Glow:** Fanatical post-exchange cultists who view the nuclear fire as divine purging. They occupy high-rad zones and utilize psychological warfare.")
p("4. **Scavenger Warlords:** Opportunistic raider gangs that exploit weak shelters, extort traders, and execute hatch raids.")
p("5. **Safe Haven Communities / Rebuilders:** Fragile civilian collectives attempting to rebuild water filtration plants, libraries, and trade networks.")
p()
p("---")
p()
p("## CHAPTER 3: CODEBASE ARCHITECTURE & SYSTEM DESIGN")
p()
p("### 3.1 Stack & Frameworks")
p("- **Engine:** Unity 6 LTS (2D URP Renderer with custom 2D lighting profiles).")
p("- **Language:** C# (NET standard 2.1).")
p("- **UI Framework:** UI Toolkit (UXML templates + USS stylesheets + C# UI View Controllers).")
p("- **Architecture Pattern:** Decoupled Data-Driven Systems Architecture.")
p("  - **Pure Logic Systems:** Plain C# classes handling math, simulation, and state modification.")
p("  - **Thin MonoBehaviours:** View controllers handling input, rendering, and UI binding only.")
p("  - **Event Bus:** Strong-typed Pub/Sub C# `EventBus` for all state mutations.")
p("  - **ScriptableObject Catalogs:** Source-of-truth runtime catalogs populated by automated JSON importers.")
p()
p("### 3.2 Namespace & Directory Map")
p("The codebase strictly follows the namespace scheme `AtomicWar._Game.<Module>`:")
p()
for folder, files in sorted(by_folder.items()):
    p(f"#### Module `AtomicWar._Game.{folder}` ({len(files)} files)")
    for f in sorted(files):
        fname = os.path.basename(f)
        p(f"- `{fname}`")
    p()

p("### 3.3 Data Pipeline & Import Tooling")
p("1. **Authored Raw Data:** Located in `Assets/StreamingAssets/Data/*.json` (`items.json`, `recipes.json`, `survivors.json`, `events.json`, `echoes.json`, `radio.json`, `locations.json`).")
p("2. **Editor Importers:** `JsonDataImporter.cs` parses raw JSON into temporary ScriptableObject instances.")
p("3. **Catalog Generation:** `CatalogGenerator.cs` compiles individual SOs into master catalog assets (`ItemCatalogSO`, `RecipeCatalogSO`, `SurvivorCatalogSO`, `LocationCatalogSO`, `GameEventCatalogSO`, `RadioCatalogSO`).")
p("4. **Runtime Access:** Gameplay systems query catalogs by unique `snake_case` IDs.")
p()
p("### 3.4 Persistence & Save System (`SaveSystem.cs`)")
p("- System states are stored in lightweight, serializable C# structs/classes containing only primitive types (ints, floats, bools, strings, arrays).")
p("- Supports multiple save slots with atomic JSON writes to prevent corruption.")
p("- On game load, systems register with `SaveSystem` and re-hydrate their state sequentially without relying on Scene GameObject references.")
p()
p("---")
p()
p("## CHAPTER 4: DETAILED GAMEPLAY MECHANICS (SYSTEM DEEP DIVE)")
p()
p("### 4.1 Survivor & Needs Simulation")
p("- **Core Needs (`Needs.cs`, `NeedsSystem.cs`):**")
p("  - `Hunger` (0-100): Decays per hour. Triggers Weakened -> Malnourished -> Starving -> Death.")
p("  - `Thirst` (0-100): Decays rapidly per hour. Triggers Dehydrated -> Severe Dehydration -> Death.")
p("  - `Fatigue` (0-100): Accumulates during work/expeditions. Restored by sleeping in Beds/Bunks.")
p("  - `Warmth` (0-100): Depends on room temperature and clothing. Hypothermia causes health loss.")
p("  - `Morale` (0-100): Affected by deaths, hunger, room aesthetics, cleanliness. Low morale causes Mental Breaks.")
p("  - `Health` (0-100): Overall physical condition. Depleted by trauma, radiation, sickness, starvation.")
p("- **Psychological & Social Systems:**")
p("  - `BeliefSystem.cs`: Faith, Pragmatism, Collectivism profiles altering survivor reactions to moral dilemmas.")
p("  - `MentalBreakSystem.cs`: Triggers Apathy, Panic Attack, Violent Outburst, or Mutiny when Morale hits zero.")
p("  - `BunkerSocialSystems.cs`: Manages Romance, Feuds, Mentorship, Imprisonment, Banishment, Pregnancy, and Black Market smuggling between shelter occupants.")
p("  - `Perk Systems`: Combat, Expedition, Medical, Shelter, Social, and Survival perks earned through experience.")
p()
p("### 4.2 Radiation & Contamination Systems")
p("- **`RadiationSystem.cs`:** Tracks ambient radiation dose (mSv/h) and total absorbed dose (mSv).")
p("- **Pathology & Dosimetry:**")
p("  - `Dosimeter.cs` & `GeigerCounter.cs`: Provide diegetic clicking sounds and visual rad readings.")
p("  - `Iodine Pills`: Saturated thyroid prophylaxis (blocks rad absorption for 24h).")
p("  - `Anti-Rad / Chelation`: Cleanses internal accumulated radiation dose.")
p("  - `Hazmat Suits`: Degrade in durability while protecting against high fallout zones.")
p("  - `RadiationMutagenesisSystem.cs`: Manages Acute Radiation Sickness (ARS) and long-term mutations/chronic illness.")
p()
p("### 4.3 Medical & Pathology Engine")
p("- **`MedicalSystem.cs`:** Models active afflictions (`ActiveAffliction.cs`): Wound Bleeding, Trauma, Bacterial Infection, Food Poisoning, Frostbite, Acute Sickness.")
p("- **Advanced Medical Features:**")
p("  - `BloodTransfusionSystem.cs`: Full ABO blood group compatibility matrix (A, B, AB, O). Mis-matched transfusions trigger lethal hemolytic reactions.")
p("  - `AddictionSystem.cs`: Tracks dependence on painkillers, stimulants, and alcohol.")
p("  - `AmputationSystem.cs`: Last-resort surgical intervention for infected/gangrenous limbs.")
p("  - `ScurvySystem.cs`: Nutritional deficiency tracking requiring Vitamin C / fresh produce.")
p()
p("### 4.4 Environment, Weather & Map Generation")
p("- **`WeatherSystem.cs`:** Simulates 16 distinct post-nuclear weather conditions:")
p("  - *Acid Snow, Bio Fog, Black Snow, Blood Rain, Dead Wind, Deep Freeze, Dust Devil, EMP Storm, False Spring, Glass Storm, Ozone Hole, Rad Hail, Silent Spring, Solar Flare, Static Charge, Algae Bloom.*")
p("- **`TemperatureSystem.cs`:** Calculates outside temperature based on season and nuclear winter index, driving shelter heating requirements.")
p("- **`FalloutMap.cs` & `GeneratedMap.cs`:** Dynamic 2D map node system with fog of war, river crossings (`RiverNodeSystem.cs`), and radiation knowledge uncertainty.")
p()
p("### 4.5 Shelter Infrastructure & Engineering")
p("- **`Shelter.cs` Aggregate:** Manages modular rooms (Bunkhouse, Medical Bay, Hydroponics, Power Room, Decontamination, Workshop, Radio Room).")
p("- **Infrastructure Subsystems:**")
p("  - `PowerNetwork.cs`: Diesel Generators, Solar Panels, Wind Turbines, Manual Crank Generators. Tracks supply vs demand.")
p("  - `AirFiltrationModuleSO.cs`: Air scrubbing filters that degrade over time. Clogged filters flood the shelter with fallout air.")
p("  - `ShelterAtmosphereSystem.cs`: Tracks oxygen, CO2, toxin levels, and humidity.")
p("  - `StructuralIntegritySystem.cs` & `MaterialShieldingSystem.cs`: Lead, concrete, and steel upgrades for radiation attenuation and raid defense.")
p("  - `HatchDefenseSystem.cs`: Perimeter traps, lock levels, noise control, and hatch defense combat resolution.")
p("  - `VerminSystem.cs` & `WasteSystem.cs`: Trash accumulation leads to rat infestations and disease vectors.")
p()
p("### 4.6 Crafting, Workbench & Economy")
p("- **`CraftingSystem.cs`:** Validates ingredients, required station levels, crafting time, and tool wear.")
p("- **`WorkbenchSystem.cs`:** Workbench upgrades, weapon maintenance, jury-rigging broken gear, and scrapping items into raw metals, electronic parts, and cloth.")
p("- **`DynamicEconomySystem.cs`:** Dynamic trade valuation based on survivor demand, faction trust, and scarcity tiers (Basic, Medical, Tactical, Luxury).")
p()
p("### 4.7 Radio & Intel Interception System")
p("- **`RadioTunerSystem.cs`:** Shortwave tuner searching frequencies:")
p("  - *Civilian (88.5 FM), Military (102.1 FM), Emergency Automated Loops, Numbers Station (99.0 FM), Survivor Frequencies.*")
p("- **Intel Types & Reliability:** Intercepts Plume Reports, Weather Forecasts, Mortar Warnings, Troop Movements, and Cache Coordinates. Intel degrades in confidence (1.0 -> 0.0) over 5 days.")
p()
p("### 4.8 Utility AI Engine (`AtomicWar._Game.AI`)")
p("- Autonomous survivor behavior engine operating without runtime LLMs.")
p("- **Scoring Formula:** `Score = BaseUtility * NeedMultiplier * TraitWeight * SafetyFactor`.")
p("- Evaluates candidate actions (Sleep, Eat Rations, Purify Water, Repair Air Filter, Scavenge, Treat Patient, Rest by Heater) every tick and assigns the highest-scoring action to autonomous survivors.")
p()
p("### 4.9 Narrative Event Engine & Victory Paths")
p("- **`EventRunner.cs`:** Weighted event picker evaluating daily preconditions, survivor traits, and shelter state.")
p("- **`GameEvent.cs`:** Branching choices with immediate effects, skill checks, and delayed consequences (`ActiveDelayedConsequence`).")
p("- **8 Victory Paths:**")
p("  1. *MAD (Mutually Assured Destruction)*: Triggering automated retaliation networks.")
p("  2. *Migration*: Escaping the fallout zone via long-range convoy.")
p("  3. *The Broadcast*: Establishing a regional emergency radio network.")
p("  4. *The Cure*: Synthesizing an anti-radiation genetic compound.")
p("  5. *The Martian*: Achieving complete closed-loop shelter self-sufficiency.")
p("  6. *True Ending*: Negotiating peace between remaining faction remnants.")
p("  7. *Underground City*: Expanding the sub-pen into a permanent subterranean settlement.")
p("  8. *Unifier*: Subjugating rival wasteland factions under one banner.")
p()
p("---")
p()
p("## CHAPTER 5: EXHAUSTIVE AUTHORED DATA CATALOGS")
p()
p(f"### 5.1 Item Catalog ({len(items)} Items)")
p("Below is the complete dataset of all 321 authored items in `items.json`:")
p()
p("| ID | Name | Type | Stack Max | Weight (kg) | Rad Prot | Durability | Trade Value | Description |")
p("| --- | --- | --- | --- | --- | --- | --- | --- | --- |")
for item in items:
    iid = item.get('id', '')
    name = item.get('displayName', '')
    itype = item.get('type', '')
    stack = item.get('stackMax', 1)
    weight = item.get('weight', 0.0)
    rad_prot = item.get('radProtection', 0.0)
    dur = item.get('durability', 0)
    trade = item.get('tradeValue', 0)
    desc = item.get('description', '').replace('\n', ' ')
    p(f"| `{iid}` | {name} | {itype} | {stack} | {weight} | {rad_prot} | {dur} | {trade} | {desc} |")

p()
p(f"### 5.2 Crafting Recipes ({len(recipes)} Recipes)")
p("Below is the complete dataset of all 16 crafting recipes in `recipes.json`:")
p()
for r in recipes:
    rid = r.get('id', '')
    rname = r.get('recipeName', '')
    ing = ", ".join([f"{i.get('amount',1)}x {i.get('itemId','')}" for i in r.get('ingredients', [])])
    res = f"{r.get('resultAmount',1)}x {r.get('resultItemId','')}"
    time_h = r.get('craftingTimeHours', 1)
    st = r.get('requiredStationId', 'workbench')
    p(f"- **`{rid}` ({rname}):** Requires `{ing}` at station `{st}` ({time_h}h) -> Produces `{res}`.")

p()
p(f"### 5.3 Survivor Archetypes ({len(survivors)} Survivors)")
p("Below is the complete dataset of all 72 survivors in `survivors.json`:")
p()
p("| ID | Name | Profession | Base Health | Bio |")
p("| --- | --- | --- | --- | --- |")
for s in survivors:
    sid = s.get('id', '')
    sname = s.get('displayName', '')
    prof = s.get('profession', '')
    hp = s.get('baseHealth', 100)
    bio = s.get('bio', '').replace('\n', ' ')
    p(f"| `{sid}` | {sname} | {prof} | {hp} | {bio} |")

p()
p(f"### 5.4 Scavenging Locations ({len(locations)} Locations)")
p("Below is the complete dataset of all 5 locations in `locations.json`:")
p()
for loc in locations:
    lid = loc.get('id', '')
    lname = loc.get('displayName', '')
    danger = loc.get('dangerLevel', 1)
    travel = loc.get('travelHours', 1)
    rads = loc.get('baseRadsPerHour', 0)
    desc = loc.get('description', '').replace('\n', ' ')
    p(f"- **`{lid}` ({lname}):** Danger Level {danger} | Travel Time: {travel}h | Base Rads: {rads} mSv/h. Description: *{desc}*")

p()
p(f"### 5.5 Narrative Events ({len(events)} Events)")
p("Below is a sample overview of authored game events in `events.json`:")
p()
for ev in events:
    eid = ev.get('id', '')
    title = ev.get('title', '')
    weight = ev.get('weight', 1)
    min_day = ev.get('minDay', 1)
    body = ev.get('bodyText', '').replace('\n', ' ')
    p(f"- **`{eid}` - {title}** (Min Day: {min_day}, Weight: {weight}): *{body}*")

p()
p(f"### 5.6 Echoes of the Past ({len(echoes)} Echoes)")
p("Below is the dataset of survivor echoes in `echoes.json`:")
p()
for ech in echoes:
    ecid = ech.get('id', '')
    title = ech.get('title', '')
    body = ech.get('bodyText', '').replace('\n', ' ')
    p(f"- **`{ecid}` - {title}**: *{body}*")

p()
p(f"### 5.7 Radio Broadcast Archive (50 Broadcasts from IntelBible)")
p()
p(intel_bible_text)

p()
p("---")
p()
p("## CHAPTER 6: USER INTERFACE & DIEGETIC HUD")
p()
p("### 6.1 UI Toolkit Architecture")
p("- **Master Controller:** `HUD.cs` binds UI View Controllers to system events.")
p("- **Widgets:**")
p("  - `NeedsBar.cs`: Displays Survivor hunger, thirst, fatigue, warmth, morale, health.")
p("  - `DosimeterHUD.cs`: Visual needle gauge and digital mSv counter.")
p("  - `EventModalUI.cs`: Narrative decision window with choice buttons and skill odds.")
p("  - `MapScreenUI.cs`: 2D node map navigation and expedition planner.")
p("  - `TradeScreenUI.cs`: Dual-column barter interface calculating trade values.")
p("  - `WorkbenchUI.cs`: Recipe selection, ingredient validation, crafting progress bar.")
p("  - `JournalBookUI.cs` & `MoralChronicleUI.cs`: Story history, survivor logs, and moral records.")
p("  - `PowerGridHUD.cs`: Shelter power generation vs consumption graph.")
p("  - `RoomAssignmentHUD.cs`: Drag-and-drop survivor bed/workstation assignment.")
p("  - `DiegeticHudController.cs` & `InternalHorrorHUD.cs`: Emergency overlays for shelter fires, corpse disposal, and hatch breaches.")
p()
p("### 6.2 Diegetic Audio Integration")
p("- `GeigerAudioHook.cs`: Converts ambient rad dose into dynamic audio click frequency.")
p("- `FactionRadioVoHook.cs`: Triggers static bursts, numbers station tones, and radio chatter.")
p()
p("---")
p()
p("## CHAPTER 7: CURRENT DEVELOPMENT PROGRESS & TEST STATUS")
p()
p("### 7.1 Implemented & Verified Systems")
p("- [x] Core Session Lifecycle (`GameState`, `TimeSystem`, `EventBus`).")
p("- [x] Persistence Layer (`SaveSystem` multi-slot JSON serialization).")
p("- [x] Survivor Needs Decay & Psychological Thresholds.")
p("- [x] Radiation Dosage, Iodine Prophylaxis, and Dosimeter Audio/Visuals.")
p("- [x] Comprehensive Medical Pathologies (Blood Transfusions, Scurvy, Amputation).")
p("- [x] Weather Engine (16 Weather Kinds & Temperature Simulation).")
p("- [x] Shelter Subsystems (Power Grid, Air Scrubbers, Material Shielding, Hatch Defense).")
p("- [x] Utility AI Autonomous Decision System.")
p("- [x] Authoring Data Pipeline (JSON -> ScriptableObjects -> Runtime Catalogs).")
p("- [x] Main Menu & In-Game UI Toolkit HUD Bindings.")
p()
p("### 7.2 Automated Test Suite Results")
p("- **EditMode Suite (`AtomicWar.Tests.EditMode`):** GREEN (All pure C# logic tests passing).")
p("- **PlayMode Suite (`AtomicWar.Tests.PlayMode`):** GREEN (Frame-by-frame Integration and `GameplaySceneSmokeTests` passing).")
p()
p("---")
p()
p("## CHAPTER 8: BRAINSTORMING PROMPTS FOR OTHER LLMS")
p()
p("Copy any of the prompts below into **Qwen**, **Gemini**, **ChatGPT**, **Claude**, **Perplexity**, or **Vibe Le Chat** alongside this file:")
p()
p("### Prompt A: New Scavenging Encounters & Location Expansion")
p("```")
p("Based on the ASHFALL master document above, design 5 new scavenging locations (following the LocationDefinitionSO schema) and 10 narrative event encounters. Maintain the cold, exhausted, non-fantasy post-nuclear tone. Output raw JSON format compatible with events.json and locations.json.")
p("```")
p()
p("### Prompt B: Deepening Social & Faction Dynamics")
p("```")
p("Using the FactionSO, BunkerSocialSystems, and EventRunner architecture described in Chapter 3 & 4 of the ASHFALL document, propose a complete sub-system design for 'Faction Favors & Betrayals'. Detail the C# system class, state serialization, and 4 multi-stage questlines.")
p("```")
p()
p("### Prompt C: Advanced Tactical Hatch Defense & Raid Mechanics")
p("```")
p("Review the HatchDefenseSystem and Shelter Infrastructure in Chapter 4. Design an expanded 2D tactical hatch defense mini-game concept that integrates perimeter traps, night vision gear, weapon maintenance, and survivor combat perks without breaking the thin MonoBehaviour / C# systems architecture.")
p("```")
p()
p("### Prompt D: Balance & Scarcity Tuning")
p("```")
p("Examine the 321 items and 16 recipes in Chapter 5. Analyze the resource conversion loops (water purification, filter crafting, medical chelation). Identify potential exploit loops and provide a re-balanced JSON trade value and recipe ingredient matrix for Hardcore Survival Mode.")
p("```")

# Write to project root master doc file
with open('ASHFALL_GAME_MASTER_DOCUMENT.md', 'w', encoding='utf-8') as f:
    f.write("\n".join(output_lines))

print(f"Generated ASHFALL_GAME_MASTER_DOCUMENT.md successfully! Total lines: {len(output_lines)}")

