using System;
using System.Collections.Generic;
using UnityEngine;

namespace AtomicWar._Game.Inventory
{
    /// <summary>
    /// Expiration state for medical supplies and food items.
    /// Fresh = full effectiveness, Expired = reduced, Degraded = severely reduced.
    /// </summary>
    public enum ExpirationState
    {
        Fresh,
        Expired,
        Degraded
    }

    /// <summary>
    /// Procedural Item Instance — runtime wrapper around ItemDefinition that
    /// adds dynamic condition, contamination, purity/calorie variance, and
    /// expiration state. Generated by ProceduralLootGenerator during scavenging.
    ///
    /// Plain C#, save-safe. All fields are primitives or enums.
    /// </summary>
    [Serializable]
    public class ProceduralItemInstance
    {
        /// <summary>Unique instance id for save/load identification.</summary>
        public string InstanceId;

        /// <summary>The base item template id.</summary>
        public string ItemId;

        /// <summary>0..1 condition/durability. Affects effectiveness and trade value.</summary>
        public float ConditionPct = 1f;

        /// <summary>0..1 contamination level (radiation, chemical, or mold).</summary>
        public float ContaminationPct;

        /// <summary>Stack quantity (for stackable items).</summary>
        public int Quantity = 1;

        /// <summary>Custom value multiplier for purity, calories, or volume.
        /// Range: 0.5x (half value) to 1.5x (exceptional quality).</summary>
        public float CustomValueMultiplier = 1f;

        /// <summary>Expiration state for food and medical items.</summary>
        public ExpirationState Expiration = ExpirationState.Fresh;

        /// <summary>For water containers: volume in litres (0.5–5.0).</summary>
        public float ContainerVolumeLitres;

        /// <summary>For containers: integrity % (leak risk when low).</summary>
        public float ContainerIntegrityPct = 1f;

        /// <summary>For scrap/raw materials: purity grade 0..1.</summary>
        public float ScrapPurityGrade = 1f;

        /// <summary>For filters: filtration efficiency in microns (0.3–5.0).
        /// Lower = better filtration.</summary>
        public float FiltrationEfficiencyMicrons;

        /// <summary>For caloric items: actual calorie value (200–1200 kcal).</summary>
        public float CaloricValueKcal;

        /// <summary>Mold/botulism risk for food (0..1).</summary>
        public float MoldRiskPct;

        /// <summary>Radiation accumulation for food (mSv/kg).</summary>
        public float FoodRadiationAccumulation;

        /// <summary>Scrap weight in kg.</summary>
        public float ScrapWeightKg;

        /// <summary>Number of doses remaining for medical items (1–5).</summary>
        public int DosesRemaining = 1;

        public ProceduralItemInstance() { }

        public ProceduralItemInstance(string itemId, int quantity = 1,
            float condition = 1f, float contamination = 0f)
        {
            InstanceId = Guid.NewGuid().ToString("N").Substring(0, 8);
            ItemId = itemId;
            Quantity = quantity;
            ConditionPct = Mathf.Clamp01(condition);
            ContaminationPct = Mathf.Clamp01(contamination);
        }

        /// <summary>
        /// Effective trade value multiplier accounting for condition and contamination.
        /// </summary>
        public float EffectiveValueMultiplier
        {
            get
            {
                float mult = CustomValueMultiplier;
                mult *= Mathf.Lerp(0.3f, 1.0f, ConditionPct);
                mult *= 1f - (ContaminationPct * 0.5f);
                if (Expiration == ExpirationState.Degraded) mult *= 0.3f;
                else if (Expiration == ExpirationState.Expired) mult *= 0.6f;
                return Mathf.Max(0.1f, mult);
            }
        }

        /// <summary>Display label for condition: Pristine / Worn / Damaged / Ruined.</summary>
        public string ConditionLabel
        {
            get
            {
                if (ConditionPct > 0.90f) return "Pristine";
                if (ConditionPct > 0.70f) return "Good";
                if (ConditionPct > 0.40f) return "Worn";
                if (ConditionPct > 0.15f) return "Damaged";
                return "Ruined";
            }
        }

        /// <summary>Display label for contamination: Clean / Trace / Contaminated / Hot.</summary>
        public string ContaminationLabel
        {
            get
            {
                if (ContaminationPct < 0.05f) return "Clean";
                if (ContaminationPct < 0.20f) return "Trace";
                if (ContaminationPct < 0.50f) return "Contaminated";
                return "Hot";
            }
        }
    }
}
