using System;
using System.Collections.Generic;
using UnityEngine;
using AtomicWar._Game.Survivors;

namespace AtomicWar._Game.Shelter
{
    /// <summary>
    /// Protocol Zero — Atmosphere Toxicity System. Tracks O2, CO2, and CO
    /// levels in the sealed bunker environment.
    ///
    /// The Suffocation Loop: Running combustion heaters in sealed rooms
    /// generates CO. Human respiration produces CO2. If ventilation is
    /// turned off to conserve heat, toxic gases accumulate.
    ///
    /// Thresholds:
    ///   20,000 ppm CO2 → Hypoxia (crafting -50%, hallucinations)
    ///   40,000 ppm CO2 → Asphyxiation (health drain, death in sleep)
    ///   CO > 400 ppm → Carbon Monoxide poisoning (confusion, nausea)
    ///
    /// Counterplay: CO2 scrubber cartridges or risk opening the hatch
    /// (instantly losing 20% room heat).
    ///
    /// Save/load safe. Plain C#.
    /// </summary>
    [Serializable]
    public class AtmosphereToxicitySave
    {
        public string systemId = "atmosphere_toxicity";
        public float co2Ppm;
        public float coPpm;
        public float o2Percent = 20.9f;
        public bool ventilationActive = true;
        public int scrubberCartridgesInstalled;
        public float scrubberHoursRemaining;
        public bool hatchSealed;
    }

    /// <summary>
    /// Events raised when toxicity thresholds are crossed.
    /// </summary>
    public struct ToxicityThresholdEvent
    {
        public string SurvivorId;
        public string GasType; // "CO2", "CO", "O2"
        public float CurrentLevel;
        public bool IsHypoxia;    // CO2 > 20k ppm
        public bool IsAsphyxiation; // CO2 > 40k ppm
        public bool IsCOPoisoning;  // CO > 400 ppm
        public bool IsOxygenLow;    // O2 < 16%
    }

    public class AtmosphereToxicitySystem
    {
        /// <summary>CO2 threshold for Hypoxia affliction (ppm).</summary>
        public const float HypoxiaThresholdPpm = 20000f;

        /// <summary>CO2 threshold for Asphyxiation (ppm).</summary>
        public const float AsphyxiationThresholdPpm = 40000f;

        /// <summary>CO threshold for carbon monoxide poisoning (ppm).</summary>
        public const float COThresholdPpm = 400f;

        /// <summary>O2 threshold for oxygen deprivation (%).</summary>
        public const float O2LowThresholdPercent = 16f;

        /// <summary>CO2 generated per survivor per hour (ppm).</summary>
        public const float CO2PerSurvivorPerHour = 800f;

        /// <summary>CO generated by combustion heater per hour (ppm).</summary>
        public const float COPerHeaterPerHour = 120f;

        /// <summary>Natural ventilation decay rate per hour with vent open.</summary>
        public const float VentilationDecayRate = 0.3f;

        /// <summary>CO2 scrubbed per cartridge per hour.</summary>
        public const float ScrubberRemovalRatePpm = 3000f;

        /// <summary>Scrubber cartridge lifespan in hours.</summary>
        public const float ScrubberLifespanHours = 48f;

        /// <summary>Heat lost when hatch is opened for emergency vent (%).</summary>
        public const float EmergencyVentHeatLossPercent = 0.20f;

        // ── Events ────────────────────────────────────────────────────
        public event Action<ToxicityThresholdEvent> OnThresholdCrossed;
        public event Action<float, float, float> OnAtmosphereChanged; // co2, co, o2
        public event Action OnVentilationToggled;
        public event Action OnScrubberExpired;

        // ── State ─────────────────────────────────────────────────────
        private float _co2Ppm;
        private float _coPpm = 5f;
        private float _o2Percent = 20.9f;
        private bool _ventilationActive = true;
        private int _scrubberCartridgesInstalled;
        private float _scrubberHoursRemaining;
        private bool _hatchSealed;
        private bool _hypoxiaTriggered;
        private bool _asphyxiationTriggered;
        private bool _coPoisoningTriggered;
        private bool _oxygenLowTriggered;

        public float CO2Ppm => _co2Ppm;
        public float COPpm => _coPpm;
        public float O2Percent => _o2Percent;
        public bool VentilationActive => _ventilationActive;
        public bool IsHypoxiaActive => _co2Ppm >= HypoxiaThresholdPpm;
        public bool IsAsphyxiationActive => _co2Ppm >= AsphyxiationThresholdPpm;
        public bool IsCOPoisoningActive => _coPpm >= COThresholdPpm;
        public int ScrubberCartridgesRemaining => _scrubberCartridgesInstalled;

        // ── Tick ──────────────────────────────────────────────────────
        /// <summary>
        /// Called every game-hour. Models gas accumulation based on
        /// survivor count, heater state, and ventilation.
        /// </summary>
        public void Tick(float gameHours, int survivorCount, bool heaterRunning)
        {
            if (gameHours <= 0f) return;

            // CO2 from breathing
            float co2Added = CO2PerSurvivorPerHour * survivorCount * gameHours;

            // CO from combustion
            float coAdded = heaterRunning ? COPerHeaterPerHour * gameHours : 0f;

            // O2 consumed (coupled to CO2)
            float o2Consumed = co2Added * 0.0001f * gameHours;

            // Ventilation removes gases
            float removalRate = _ventilationActive ? VentilationDecayRate : 0.02f;

            // Scrubber removes CO2
            float scrubberRemoval = 0f;
            if (_scrubberCartridgesInstalled > 0 && _scrubberHoursRemaining > 0f)
            {
                scrubberRemoval = ScrubberRemovalRatePpm * gameHours;
                _scrubberHoursRemaining = Mathf.Max(0f, _scrubberHoursRemaining - gameHours);
                if (_scrubberHoursRemaining <= 0f)
                {
                    _scrubberCartridgesInstalled--;
                    OnScrubberExpired?.Invoke();
                    if (_scrubberCartridgesInstalled > 0)
                        _scrubberHoursRemaining = ScrubberLifespanHours;
                }
            }

            // Apply accumulation
            _co2Ppm = Mathf.Max(0f, _co2Ppm + co2Added - (_co2Ppm * removalRate * gameHours) - scrubberRemoval);
            _coPpm = Mathf.Max(0f, _coPpm + coAdded - (_coPpm * removalRate * gameHours));
            _o2Percent = Mathf.Clamp(_o2Percent - o2Consumed + (removalRate * gameHours * 0.5f), 5f, 21f);

            OnAtmosphereChanged?.Invoke(_co2Ppm, _coPpm, _o2Percent);

            // Threshold checks
            CheckThresholds();
        }

        private void CheckThresholds()
        {
            bool newHypoxia = _co2Ppm >= HypoxiaThresholdPpm && !_hypoxiaTriggered;
            bool newAsphyxiation = _co2Ppm >= AsphyxiationThresholdPpm && !_asphyxiationTriggered;
            bool newCO = _coPpm >= COThresholdPpm && !_coPoisoningTriggered;
            bool newO2Low = _o2Percent <= O2LowThresholdPercent && !_oxygenLowTriggered;

            if (newHypoxia || newAsphyxiation || newCO || newO2Low)
            {
                _hypoxiaTriggered = _hypoxiaTriggered || newHypoxia;
                _asphyxiationTriggered = _asphyxiationTriggered || newAsphyxiation;
                _coPoisoningTriggered = _coPoisoningTriggered || newCO;
                _oxygenLowTriggered = _oxygenLowTriggered || newO2Low;

                OnThresholdCrossed?.Invoke(new ToxicityThresholdEvent
                {
                    GasType = newCO ? "CO" : (newAsphyxiation ? "CO2" : (newHypoxia ? "CO2" : "O2")),
                    CurrentLevel = newCO ? _coPpm : _co2Ppm,
                    IsHypoxia = newHypoxia,
                    IsAsphyxiation = newAsphyxiation,
                    IsCOPoisoning = newCO,
                    IsOxygenLow = newO2Low
                });
            }

            // Reset triggers when levels drop below threshold
            if (_co2Ppm < HypoxiaThresholdPpm * 0.5f) { _hypoxiaTriggered = false; _asphyxiationTriggered = false; }
            if (_coPpm < COThresholdPpm * 0.5f) _coPoisoningTriggered = false;
            if (_o2Percent > O2LowThresholdPercent + 2f) _oxygenLowTriggered = false;
        }

        // ── Actions ───────────────────────────────────────────────────
        /// <summary>Toggle ventilation on/off. Turning off conserves heat.</summary>
        public void ToggleVentilation()
        {
            _ventilationActive = !_ventilationActive;
            OnVentilationToggled?.Invoke();
        }

        /// <summary>Install a CO2 scrubber cartridge.</summary>
        public bool InstallScrubber()
        {
            _scrubberCartridgesInstalled++;
            if (_scrubberHoursRemaining <= 0f)
                _scrubberHoursRemaining = ScrubberLifespanHours;
            return true;
        }

        /// <summary>
        /// Emergency vent: open the hatch. Clears 80% of CO2/CO instantly
        /// but loses 20% of room heat. Returns the fraction of heat lost.
        /// </summary>
        public float EmergencyVent()
        {
            _co2Ppm *= 0.2f;
            _coPpm = Mathf.Max(0f, _coPpm - 200f);
            _o2Percent = Mathf.Min(21f, _o2Percent + 3f);
            _hatchSealed = false;

            _hypoxiaTriggered = false;
            _asphyxiationTriggered = false;
            _coPoisoningTriggered = false;

            return EmergencyVentHeatLossPercent;
        }

        /// <summary>Called when the hatch is sealed again after emergency vent.</summary>
        public void SealHatch()
        {
            _hatchSealed = true;
        }

        // ── Save / Load ────────────────────────────────────────────────
        public AtmosphereToxicitySave CaptureState()
        {
            return new AtmosphereToxicitySave
            {
                co2Ppm = _co2Ppm,
                coPpm = _coPpm,
                o2Percent = _o2Percent,
                ventilationActive = _ventilationActive,
                scrubberCartridgesInstalled = _scrubberCartridgesInstalled,
                scrubberHoursRemaining = _scrubberHoursRemaining,
                hatchSealed = _hatchSealed
            };
        }

        public void RestoreState(AtmosphereToxicitySave save)
        {
            if (save == null)
            {
                _co2Ppm = 0f;
                _coPpm = 5f;
                _o2Percent = 20.9f;
                _ventilationActive = true;
                _scrubberCartridgesInstalled = 0;
                _scrubberHoursRemaining = 0f;
                _hatchSealed = false;
                _hypoxiaTriggered = false;
                _asphyxiationTriggered = false;
                _coPoisoningTriggered = false;
                _oxygenLowTriggered = false;
                return;
            }

            _co2Ppm = save.co2Ppm;
            _coPpm = save.coPpm;
            _o2Percent = save.o2Percent;
            _ventilationActive = save.ventilationActive;
            _scrubberCartridgesInstalled = save.scrubberCartridgesInstalled;
            _scrubberHoursRemaining = save.scrubberHoursRemaining;
            _hatchSealed = save.hatchSealed;
        }
    }
}
