#!/usr/bin/env python3
"""Generate the authoritative ASHFALL plan register.

The register is a projection of plan front matter and the repository.  It is
never edited by hand.  Legacy plans remain visible with ``METADATA_MISSING``
status until the staged metadata migration (E1C) gives them author-owned
fields.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
sys.path.insert(0, str(SCRIPT_DIR))

from plan_corpus_lib import (  # noqa: E402
    CATEGORIES,
    GENERATED_STATUSES,
    METADATA_SCHEMA_VERSION,
    REGISTER_SCHEMA_VERSION,
    STATUSES,
    analyze_references,
    classify_doc,
    detect_supersedence_cycles,
    enumerate_docs,
    enumerate_paths,
    git_value,
    normalize_metadata,
    parse_front_matter,
    parse_plan,
    sha256_file,
    stable_file_lists,
    utc_now,
)


CONFIG_PATH = SCRIPT_DIR / "plan_governance_config.json"
BASELINE_DIR = REPO_ROOT / "docs" / "roadmap" / "e1"
REGISTER_JSON = REPO_ROOT / "docs" / "roadmap" / "PLAN_REGISTER.json"
REGISTER_MD = REPO_ROOT / "docs" / "roadmap" / "PLAN_REGISTER.md"
GENERATED_BANNER = "<!-- GENERATED BY scripts/ci/generate-plan-register.py — DO NOT EDIT -->"


def load_config(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def namespace_for(path: Path, config: dict[str, Any], repo_root: Path) -> str:
    relative = path.relative_to(repo_root)
    for namespace in config.get("plan_namespaces", []):
        root = Path(str(namespace["root"]))
        try:
            relative.relative_to(root)
            return str(namespace.get("name", root.as_posix()))
        except ValueError:
            continue
    return relative.parts[0]


def parse_iso_date(value: Any) -> datetime | None:
    if not value or not isinstance(value, str):
        return None
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=timezone.utc)
        return parsed
    except ValueError:
        return None


def premise_age_days(value: Any) -> int | None:
    parsed = parse_iso_date(value)
    if parsed is None:
        return None
    return max(0, (datetime.now(timezone.utc) - parsed).days)


def rails_summary(rails: list[str]) -> dict[str, Any]:
    if not rails:
        return {"state": "UNDECLARED", "required": []}
    return {"state": "UNRESOLVED", "required": sorted(rails)}


def register_rows(repo_root: Path, config: dict[str, Any]) -> tuple[list[dict[str, Any]], list[str]]:
    rows: list[dict[str, Any]] = []
    diagnostics: list[str] = []
    for path in enumerate_paths(repo_root, config):
        relative = path.relative_to(repo_root).as_posix()
        text = path.read_text(encoding="utf-8")
        record = parse_plan(path, repo_root)
        references, reference_health = analyze_references(text, repo_root, record["metadata_state"] == "METADATA_MISSING")
        record["references"] = references
        record["reference_health"] = reference_health
        record["namespace"] = namespace_for(path, config, repo_root)
        row = {
            "plan_id": record["plan_id"],
            "metadata_schema_version": METADATA_SCHEMA_VERSION,
            "metadata_state": record["metadata_state"],
            "status": record["status"],
            "status_raw": record["status_raw"],
            "category": record["category"],
            "category_raw": record["category_raw"],
            "wave": record["wave"],
            "premise_verified_at": record["premise_verified_at"],
            "premise_sha": record["premise_sha"],
            "premise_age_days": premise_age_days(record["premise_verified_at"]),
            "supersedes": sorted(record["supersedes"]),
            "superseded_by": sorted(record["superseded_by"]),
            "owner": record["owner"],
            "rails_required": sorted(record["rails_required"]),
            "rails": rails_summary(record["rails_required"]),
            "metric_moved": record["metric_moved"],
            "acceptance_tier": record["acceptance_tier"],
            "source_authority": record["source_authority"],
            "reference_health": reference_health,
            "references": references,
            "overlap_cluster": None,
            "path": relative,
            "namespace": record["namespace"],
            "filename": path.name,
            "file_sha256": sha256_file(path),
            "warnings": sorted(record["warnings"]),
            "errors": sorted(record["errors"]),
        }
        rows.append(row)
        diagnostics.extend(f"{relative}: {error}" for error in record["errors"])

    seen: dict[str, str] = {}
    for row in rows:
        previous = seen.get(row["plan_id"])
        if previous:
            message = f"duplicate PLAN_ID {row['plan_id']!r}: {previous} and {row['path']}"
            row["errors"].append(message)
            diagnostics.append(message)
        else:
            seen[row["plan_id"]] = row["path"]

    cycles = detect_supersedence_cycles(rows)
    cycle_members = {member for cycle in cycles for member in cycle}
    for row in rows:
        if row["plan_id"] in cycle_members:
            row["errors"].append("supersedence cycle: " + " -> ".join(next(cycle for cycle in cycles if row["plan_id"] in cycle)))
    for cycle in cycles:
        diagnostics.append("supersedence cycle: " + " -> ".join(cycle))

    status_rank = {
        "IN_PROGRESS": 0,
        "READY": 1,
        "PROPOSED": 2,
        "BLOCKED": 3,
        "PREMISE_STALE": 4,
        "METADATA_MISSING": 5,
        "NOT_NOW": 6,
        "MERGED": 7,
        "DONE": 8,
        "SUPERSEDED": 9,
        "DROPPED": 10,
        "ARCHIVED": 11,
    }
    rows.sort(key=lambda row: (status_rank.get(row["status"], 99), row["plan_id"], row["path"]))
    return rows, sorted(set(diagnostics))


def build_register(repo_root: Path, config: dict[str, Any]) -> dict[str, Any]:
    rows, diagnostics = register_rows(repo_root, config)
    counts: dict[str, int] = {}
    namespace_counts: dict[str, int] = {}
    metadata_counts: dict[str, int] = {}
    for row in rows:
        counts[row["status"]] = counts.get(row["status"], 0) + 1
        namespace_counts[row["namespace"]] = namespace_counts.get(row["namespace"], 0) + 1
        metadata_counts[row["metadata_state"]] = metadata_counts.get(row["metadata_state"], 0) + 1
    return {
        "register_schema_version": REGISTER_SCHEMA_VERSION,
        "metadata_schema_version": METADATA_SCHEMA_VERSION,
        "generated_by": "scripts/ci/generate-plan-register.py",
        "repository": {
            "head": git_value(repo_root, ["rev-parse", "HEAD"], "UNKNOWN"),
            "branch": git_value(repo_root, ["branch", "--show-current"], "UNKNOWN"),
        },
        "config_path": "scripts/ci/plan_governance_config.json",
        "counts": {
            "plans": len(rows),
            "by_status": dict(sorted(counts.items())),
            "by_namespace": dict(sorted(namespace_counts.items())),
            "by_metadata_state": dict(sorted(metadata_counts.items())),
        },
        "validation": {
            "errors": diagnostics,
            "legacy_status": list(GENERATED_STATUSES),
            "allowed_statuses": list(STATUSES),
            "allowed_categories": list(CATEGORIES),
        },
        "plans": rows,
    }


def json_text(document: dict[str, Any]) -> str:
    return json.dumps(document, ensure_ascii=False, indent=2, sort_keys=False) + "\n"


def cell(value: Any) -> str:
    if value is None:
        return "—"
    if isinstance(value, list):
        value = ", ".join(str(item) for item in value) or "—"
    return str(value).replace("|", "\\|").replace("\n", " ")


def markdown_text(document: dict[str, Any]) -> str:
    counts = document["counts"]
    lines = [
        GENERATED_BANNER,
        "# ASHFALL Plan Register",
        "",
        "This file is generated from plan front matter and repository state. The JSON sibling is the integration substrate; do not edit either artifact by hand.",
        "",
        f"- Register schema: `{document['register_schema_version']}`",
        f"- Repository HEAD: `{document['repository']['head']}`",
        f"- Plans: **{counts['plans']}**",
        f"- Namespaces: " + ", ".join(f"`{key}` {value}" for key, value in counts["by_namespace"].items()),
        f"- Metadata state: " + ", ".join(f"`{key}` {value}" for key, value in counts["by_metadata_state"].items()),
        "",
        "| Plan ID | Status | Category | Wave | Premise | Ref health | Rails | Metric | Overlap | Path |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for row in document["plans"]:
        premise = row["premise_verified_at"] or "—"
        if row["premise_age_days"] is not None:
            premise = f"{premise} ({row['premise_age_days']}d)"
        rails = row["rails"]["state"]
        if row["rails_required"]:
            rails += ":" + ",".join(row["rails_required"])
        lines.append(
            "| " + " | ".join(
                cell(value)
                for value in (
                    row["plan_id"],
                    row["status"],
                    row["category"],
                    row["wave"],
                    premise,
                    row["reference_health"],
                    rails,
                    row["metric_moved"],
                    row["overlap_cluster"],
                    row["path"],
                )
            ) + " |"
        )
    if document["validation"]["errors"]:
        lines.extend(["", "## Validation diagnostics", ""])
        lines.extend(f"- {diagnostic}" for diagnostic in document["validation"]["errors"])
    return "\n".join(lines) + "\n"


def baseline_document(repo_root: Path, config: dict[str, Any], gate_results: Path | None) -> dict[str, Any]:
    plan_paths = enumerate_paths(repo_root, config)
    docs = enumerate_docs(repo_root, config)
    plans_by_namespace: dict[str, int] = {}
    for path in plan_paths:
        name = namespace_for(path, config, repo_root)
        plans_by_namespace[name] = plans_by_namespace.get(name, 0) + 1
    docs_by_kind: dict[str, int] = {}
    for path in docs:
        kind = classify_doc(path.relative_to(repo_root).as_posix()[5:])
        docs_by_kind[kind] = docs_by_kind.get(kind, 0) + 1
    gate_summary: dict[str, Any] = {"state": "NOT_CAPTURED"}
    if gate_results and gate_results.is_file():
        try:
            source = json.loads(gate_results.read_text(encoding="utf-8"))
            gate_summary = {
                "state": "CAPTURED",
                "passed": source.get("passed", source.get("summary", {}).get("passed")),
                "total": source.get("total", source.get("summary", {}).get("total")),
                "failed": source.get("failed", source.get("summary", {}).get("failed")),
                "source": gate_results.relative_to(repo_root).as_posix(),
            }
        except (OSError, json.JSONDecodeError):
            gate_summary = {"state": "UNREADABLE", "source": gate_results.as_posix()}

    return {
        "baseline_schema_version": 1,
        "generated_by": "scripts/ci/generate-plan-register.py --baseline",
        "captured_at_utc": utc_now(),
        "repository": {
            "head": git_value(repo_root, ["rev-parse", "HEAD"], "UNKNOWN"),
            "branch": git_value(repo_root, ["branch", "--show-current"], "UNKNOWN"),
            "status": git_value(repo_root, ["status", "--short"], "UNKNOWN").splitlines(),
        },
        "plan_file_list": [path.relative_to(repo_root).as_posix() for path in plan_paths],
        "plan_counts": {"total": len(plan_paths), "by_namespace": dict(sorted(plans_by_namespace.items()))},
        "docs_file_list": [path.relative_to(repo_root).as_posix() for path in docs],
        "docs_counts": {"total": len(docs), "by_kind": dict(sorted(docs_by_kind.items()))},
        "gate_results": gate_summary,
        "stable_file_list": stable_file_lists(repo_root, config),
        "toolchain": {
            "python": sys.version.split()[0],
            "dotnet": command_version("dotnet", ["--version"]),
            "godot": command_version("godot", ["--version"]),
        },
    }


def command_version(command: str, args: list[str]) -> str:
    executable = shutil.which(command)
    if not executable:
        return "UNAVAILABLE"
    try:
        return subprocess.run([executable, *args], check=True, capture_output=True, text=True).stdout.strip() or "UNKNOWN"
    except (OSError, subprocess.CalledProcessError):
        return "UNKNOWN"


def write_if_changed(path: Path, content: str) -> bool:
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def run_self_test() -> None:
    import tempfile

    with tempfile.TemporaryDirectory(prefix="ashfall-plan-governance-") as temp:
        root = Path(temp)
        valid = root / "valid.md"
        valid.write_text(
            "---\nPLAN_ID: FIXTURE-VALID\nSTATUS: READY\nCATEGORY: LINK\nWAVE: E1\nRAILS_REQUIRED:\n  - docs\nMETRIC_MOVED: fixture metric\nACCEPTANCE_TIER: focused\nSOURCE_AUTHORITY: docs/roadmap/README.md\n---\n# Fixture\n",
            encoding="utf-8",
        )
        legacy = root / "legacy.md"
        legacy.write_text("# Legacy fixture\n", encoding="utf-8")
        invalid = root / "invalid.md"
        invalid.write_text("---\nPLAN_ID: FIXTURE-INVALID\nSTATUS: mostly done\nCATEGORY: UNKNOWN\n---\n", encoding="utf-8")
        from plan_corpus_lib import classify_reference

        valid_record = parse_plan(valid, root)
        assert valid_record["status"] == "READY"
        assert valid_record["rails_required"] == ["docs"]
        legacy_record = parse_plan(legacy, root)
        assert legacy_record["metadata_state"] == "METADATA_MISSING"
        assert legacy_record["plan_id"].startswith("LEGACY-")
        invalid_record = parse_plan(invalid, root)
        assert invalid_record["errors"]
        assert classify_reference("missing/file.cs:4", root).status == "MISSING_PATH"
        assert stable_file_lists(root, {"plan_namespaces": []})

    fixture_dir = SCRIPT_DIR / "fixtures" / "plan_governance"
    fixture_paths = sorted(fixture_dir.glob("*.md"))
    assert len(fixture_paths) >= 6
    fixture_records = [parse_plan(path, REPO_ROOT) for path in fixture_paths]
    assert any(record["metadata_state"] == "METADATA_MISSING" for record in fixture_records)
    assert any(record["errors"] for record in fixture_records if record["plan_id"] == "FIXTURE-INVALID-CATEGORY")
    assert len(detect_supersedence_cycles(fixture_records)) == 1
    stale_text = (fixture_dir / "stale_reference.md").read_text(encoding="utf-8")
    stale_refs, _ = analyze_references(stale_text, REPO_ROOT, legacy=False)
    assert any(item["status"] == "MISSING_PATH" for item in stale_refs)
    print("plan corpus self-test: PASS")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=CONFIG_PATH)
    parser.add_argument("--write", action="store_true", help="write generated register artifacts")
    parser.add_argument("--check", action="store_true", help="fail if generated register artifacts drift")
    parser.add_argument("--json", action="store_true", help="print register JSON to stdout")
    parser.add_argument("--explain", metavar="PLAN_ID", help="print one parsed plan row")
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--baseline", action="store_true", help="generate the E1A baseline instead of the register")
    parser.add_argument("--gate-results", type=Path, help="existing fast-gate JSON to capture in the baseline")
    parser.add_argument("--run-witnesses", action="store_true", help="reserved for phase-boundary witness capture")
    args = parser.parse_args()

    if args.self_test:
        run_self_test()
        return 0

    config_path = args.config if args.config.is_absolute() else REPO_ROOT / args.config
    config = load_config(config_path)
    if args.baseline:
        baseline = baseline_document(REPO_ROOT, config, args.gate_results)
        target = BASELINE_DIR / "e1_baseline.json"
        if target.is_file():
            try:
                previous = json.loads(target.read_text(encoding="utf-8"))
                if (
                    previous.get("repository", {}).get("head") == baseline["repository"]["head"]
                    and previous.get("plan_file_list") == baseline["plan_file_list"]
                    and previous.get("docs_file_list") == baseline["docs_file_list"]
                ):
                    baseline["captured_at_utc"] = previous.get("captured_at_utc", baseline["captured_at_utc"])
                    # A baseline is a snapshot, not a live dirty-state meter.
                    # Preserve its captured status until the file inventory or
                    # commit changes, otherwise --check would drift whenever
                    # another package adds an unrelated working-tree file.
                    baseline["repository"] = previous.get("repository", baseline["repository"])
            except (OSError, json.JSONDecodeError):
                pass
        content = json_text(baseline)
        markdown = "\n".join([
            "<!-- GENERATED BY scripts/ci/generate-plan-register.py --baseline — DO NOT EDIT -->",
            "# E1A Baseline",
            "",
            f"Captured at `{baseline['captured_at_utc']}` from `{baseline['repository']['head']}` on branch `{baseline['repository']['branch']}`.",
            "",
            f"- Plans: **{baseline['plan_counts']['total']}**",
            f"- Plan namespaces: `{baseline['plan_counts']['by_namespace']}`",
            f"- Markdown docs: **{baseline['docs_counts']['total']}**",
            f"- Docs classes: `{baseline['docs_counts']['by_kind']}`",
            f"- Fast gate capture: `{baseline['gate_results']['state']}`",
            f"- Stable file-list probe: `{baseline['stable_file_list']}`",
            "",
            "The JSON sibling preserves the sorted plan and documentation file lists used for later E1 metric deltas.",
            "",
        ])
        if args.write or not args.check:
            write_if_changed(target, content)
            write_if_changed(BASELINE_DIR / "E1_BASELINE.md", markdown)
        if args.check:
            expected_json = target.read_text(encoding="utf-8") if target.is_file() else ""
            expected_md = (BASELINE_DIR / "E1_BASELINE.md").read_text(encoding="utf-8") if (BASELINE_DIR / "E1_BASELINE.md").is_file() else ""
            if expected_json != content or expected_md != markdown:
                print("E1A baseline drift detected", file=sys.stderr)
                return 1
        return 0

    document = build_register(REPO_ROOT, config)
    if args.json:
        print(json_text(document), end="")
    if args.explain:
        matches = [row for row in document["plans"] if row["plan_id"] == args.explain]
        if len(matches) != 1:
            print(f"plan id not found or not unique: {args.explain}", file=sys.stderr)
            return 1
        print(json.dumps(matches[0], ensure_ascii=False, indent=2))
    if args.write:
        write_if_changed(REGISTER_JSON, json_text(document))
        write_if_changed(REGISTER_MD, markdown_text(document))
    if args.check:
        expected_json = REGISTER_JSON.read_text(encoding="utf-8") if REGISTER_JSON.is_file() else ""
        expected_md = REGISTER_MD.read_text(encoding="utf-8") if REGISTER_MD.is_file() else ""
        if expected_json != json_text(document) or expected_md != markdown_text(document):
            print("plan register drift detected; run with --write", file=sys.stderr)
            return 1
    if args.run_witnesses:
        print("plan register witness capture is intentionally phase-boundary only; no runtime witness was run")
    if not any((args.write, args.check, args.json, args.explain, args.run_witnesses)):
        print(f"plan register: {document['counts']['plans']} plans")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
