#!/usr/bin/env python3
"""Validate reviewed E1E overlap records and generate their Markdown report."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "docs/roadmap/e1/E1E_CAPABILITY_CLUSTERS.json"
REGISTER = ROOT / "docs/roadmap/PLAN_REGISTER.json"
OUTPUT = ROOT / "docs/roadmap/CAPABILITY_CLUSTERS.md"
BANNER = "<!-- GENERATED BY scripts/ci/generate-capability-clusters.py — DO NOT EDIT -->"
REQUIRED_RECEIPT = {"queries", "files_inspected", "live_systems_found", "reviewer_conclusion"}
RELATIONS = {"EXTENSION_CANDIDATE", "RELATED_DISTINCT", "COMPLETED_REFERENCE"}
ACTIONS = {"LINK", "CONTENT", "PRESENTATION", "SYSTEM"}


def validate_receipt_content(cluster_id: str, plan_id: str, receipt_path: str, text: str) -> list[str]:
    errors: list[str] = []
    first_heading = next((line.strip() for line in text.splitlines() if line.strip()), "")
    if not first_heading.casefold().startswith("# duplicate-search receipt"):
        errors.append(f"{cluster_id}: member receipt has invalid heading: {receipt_path}")
    if plan_id not in text:
        errors.append(f"{cluster_id}: member receipt does not name plan id {plan_id}: {receipt_path}")
    return errors


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def validate(root: Path, source: dict[str, Any], register: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    if source.get("schema_version") != 1:
        errors.append("unsupported E1E cluster schema_version")
    rows = register.get("plans", [])
    by_id: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        by_id.setdefault(str(row.get("plan_id", "")), []).append(row)
    try:
        claim_document = load_json(root / "docs/architecture/CLAIMS.json")
        known_claim_ids = {claim.get("claim_id") for claim in claim_document.get("claims", [])}
    except (OSError, json.JSONDecodeError):
        known_claim_ids = set()
        errors.append("capability claims registry is unreadable")

    for path in source.get("source_indexes", []):
        if not (root / path).exists():
            errors.append(f"source index does not exist: {path}")
    review_evidence = source.get("review_evidence", "")
    if not review_evidence or not (root / review_evidence).is_file():
        errors.append(f"review evidence does not exist: {review_evidence}")

    cluster_ids: set[str] = set()
    for cluster in source.get("clusters", []):
        cluster_id = str(cluster.get("id", ""))
        if not cluster_id:
            errors.append("cluster has no id")
            continue
        if cluster_id in cluster_ids:
            errors.append(f"duplicate cluster id: {cluster_id}")
        cluster_ids.add(cluster_id)
        if cluster.get("review_status") not in {"PENDING", "REVIEWED"}:
            errors.append(f"{cluster_id}: review_status must be PENDING or REVIEWED")
        if cluster.get("review_status") == "REVIEWED" and not cluster.get("review_conclusion"):
            errors.append(f"{cluster_id}: reviewed cluster has no reviewer conclusion")
        if cluster.get("next_action") not in ACTIONS:
            errors.append(f"{cluster_id}: invalid next_action")
        if "status" in cluster or "status" in cluster.get("review_conclusion", {}):
            errors.append(f"{cluster_id}: clusters may not assign plan statuses")

        receipt = cluster.get("duplicate_search_receipt", {})
        missing_receipt = REQUIRED_RECEIPT - set(receipt)
        if missing_receipt:
            errors.append(f"{cluster_id}: receipt missing fields {sorted(missing_receipt)}")
        for field in ("queries", "files_inspected", "live_systems_found"):
            if not isinstance(receipt.get(field), list) or not receipt[field]:
                errors.append(f"{cluster_id}: receipt field {field} must be a non-empty list")
        for path in receipt.get("files_inspected", []):
            if not (root / path).exists():
                errors.append(f"{cluster_id}: inspected file does not exist: {path}")

        member_ids: set[str] = set()
        for member in cluster.get("members", []):
            plan_id = str(member.get("plan_id", ""))
            if plan_id in member_ids:
                errors.append(f"{cluster_id}: duplicate member {plan_id}")
            member_ids.add(plan_id)
            if member.get("relation") not in RELATIONS:
                errors.append(f"{cluster_id}: invalid relation for {plan_id}")
            if len(by_id.get(plan_id, [])) != 1:
                errors.append(f"{cluster_id}: plan id must resolve uniquely in register: {plan_id}")
            receipt_path = member.get("receipt_path")
            if receipt_path:
                receipt_file = root / receipt_path
                if not receipt_file.is_file():
                    errors.append(f"{cluster_id}: member receipt does not exist: {receipt_path}")
                else:
                    try:
                        errors.extend(validate_receipt_content(
                            cluster_id, plan_id, receipt_path,
                            receipt_file.read_text(encoding="utf-8")))
                    except OSError:
                        errors.append(f"{cluster_id}: member receipt cannot be read: {receipt_path}")
        if not member_ids:
            errors.append(f"{cluster_id}: cluster has no members")

        authorities = cluster.get("live_authorities", [])
        if not authorities:
            errors.append(f"{cluster_id}: no live authority evidence")
        for authority in authorities:
            path = authority.get("path", "")
            if not path or not (root / path).exists():
                errors.append(f"{cluster_id}: authority path does not exist: {path}")
        for section in cluster.get("save_sections", []):
            registry_path = root / "Assets/Ashfall.Core/Save/SaveSectionRegistry.cs"
            if f'new("{section}"' not in registry_path.read_text(encoding="utf-8"):
                errors.append(f"{cluster_id}: save section is not registered: {section}")
        for claim_id in cluster.get("claim_ids", []):
            if claim_id not in known_claim_ids:
                errors.append(f"{cluster_id}: unknown capability claim id: {claim_id}")

    return errors


def markdown(source: dict[str, Any], register: dict[str, Any]) -> str:
    plan_by_id = {row["plan_id"]: row for row in register["plans"]}
    lines = [
        BANNER,
        "# Capability overlap clusters",
        "",
        "This report records reviewed overlap candidates. Cluster membership is evidence for linking and intake review; it never changes plan status or authorizes a merge.",
        "",
        f"- Registry schema: `{source['schema_version']}`",
        f"- Reviewed clusters: {sum(c['review_status'] == 'REVIEWED' for c in source['clusters'])}",
        f"- Review evidence: `{source['review_evidence']}`",
        f"- Source indexes: {', '.join(f'`{p}`' for p in source['source_indexes'])}",
        "",
        "## Extension before invention",
        "",
        "Before proposing a new `SYSTEM`, search the register and these clusters; name the current Core authority, host route, save owner, and acceptance tests. Prefer a bounded extension ticket when a live owner exists. Treat semantic similarity as a review lead only: distinct lifecycle, state owner, or player outcome stays separate. Never change status or merge plans from a cluster signal alone.",
    ]
    for cluster in source["clusters"]:
        lines.extend(["", f"## {cluster['id']} — {cluster['label']}", ""])
        lines.append(f"**Confidence:** {cluster['confidence']} · **Review:** {cluster['review_status']} · **Next action:** `{cluster['next_action']}`")
        lines.extend(["", cluster["review_conclusion"], "", "### Plan members", "", "| Plan ID | Path | Relation | Duplicate-search receipt |", "|---|---|---|---|"])
        for member in cluster["members"]:
            row = plan_by_id[member["plan_id"]]
            receipt_path = member.get("receipt_path")
            receipt_link = f"[`review`](../../{receipt_path})" if receipt_path else "—"
            lines.append(f"| `{member['plan_id']}` | `{row['path']}` | `{member['relation']}` | {receipt_link} |")
        lines.extend(["", "### Live authority index", "", "| Authority | Role | Evidence path |", "|---|---|---|"])
        for authority in cluster["live_authorities"]:
            lines.append(f"| `{authority['name']}` | {authority['role']} | `{authority['path']}` |")
        lines.extend(["", f"**Integration seam:** {cluster['integration_seam']}", "", "### Duplicate-search receipt", ""])
        lines.append("**Save sections:** " + (", ".join(f"`{value}`" for value in cluster.get("save_sections", [])) or "No stateful section identified."))
        lines.append("**Capability claim IDs:** " + (", ".join(f"`{value}`" for value in cluster.get("claim_ids", [])) or "No domain-specific claim currently matches in `docs/architecture/CLAIMS.json`."))
        lines.append("")
        receipt = cluster["duplicate_search_receipt"]
        for label, key in (("Queries", "queries"), ("Files inspected", "files_inspected"), ("Live systems found", "live_systems_found")):
            lines.append(f"- **{label}:** " + ", ".join(f"`{value}`" for value in receipt[key]))
        lines.append(f"- **Reviewer conclusion:** {receipt['reviewer_conclusion']}")
    signals = candidate_signals(source, register)
    lines.extend(["", "## Unreviewed deterministic signals", "", "These are lexical search leads from plan paths, category, rails, source authorities, and referenced paths. They are not cluster membership and never change plan status.", ""])
    for cluster in source["clusters"]:
        candidates = signals[cluster["id"]]
        lines.extend([f"### {cluster['id']} ({len(candidates)} candidates)", ""])
        if not candidates:
            lines.append("No additional candidates found.")
        else:
            for plan_id, path, terms in candidates:
                lines.append(f"- `{plan_id}` — `{path}` (signals: {', '.join(f'`{term}`' for term in terms)})")
    lines.extend(["", "## Receipt format", "", f"Use [`DUPLICATE_SEARCH_RECEIPT_TEMPLATE.md`](DUPLICATE_SEARCH_RECEIPT_TEMPLATE.md). Required fields are `{', '.join(sorted(REQUIRED_RECEIPT))}`.", ""])
    return "\n".join(lines)


def candidate_signals(source: dict[str, Any], register: dict[str, Any]) -> dict[str, list[tuple[str, str, list[str]]]]:
    assigned = {
        cluster["id"]: {member["plan_id"] for member in cluster["members"]}
        for cluster in source["clusters"]
    }
    found: dict[str, list[tuple[str, str, list[str]]]] = {cluster["id"]: [] for cluster in source["clusters"]}
    for row in register.get("plans", []):
        plan_path = ROOT / row.get("path", "")
        try:
            named_system_text = " ".join(plan_path.read_text(encoding="utf-8", errors="replace").splitlines()[:120])
        except OSError:
            named_system_text = ""
        searchable = " ".join([
            row.get("title", ""),
            named_system_text,
            row.get("path", ""),
            row.get("category_raw", ""),
            " ".join(row.get("rails_required", [])),
            " ".join(row.get("source_authority", [])),
            " ".join(ref.get("reference", "") for ref in row.get("references", [])),
        ]).casefold().replace("_", " ").replace("-", " ")
        for cluster in source["clusters"]:
            plan_id = row.get("plan_id", "")
            if plan_id in assigned[cluster["id"]]:
                continue
            explicit_systems = [authority.get("name", "") for authority in cluster.get("live_authorities", [])]
            terms = [term for term in [*cluster.get("vocabulary", []), *explicit_systems] if term.casefold().replace("_", " ").replace("-", " ") in searchable]
            if terms:
                found[cluster["id"]].append((plan_id, row.get("path", ""), sorted(set(terms))))
    for candidates in found.values():
        candidates.sort(key=lambda candidate: (candidate[0], candidate[1]))
    return found


def self_test() -> None:
    def classify(signal: str, vocabulary: list[str]) -> bool:
        normalized = " ".join(signal.casefold().replace("-", " ").split())
        return any(" ".join(term.casefold().replace("-", " ").split()) in normalized for term in vocabulary)

    fixture = {"clusters": [{"id": "npc-memory", "members": [{"plan_id": "A"}], "vocabulary": ["per npc memory", "memory decay"]}]}
    rows = [
        {"plan_id": "A", "path": "Plan_Per_NPC_Memory.md"},
        {"plan_id": "B", "path": "Plan_Per_NPC_Memory_Relationships.md"},
        {"plan_id": "C", "path": "Plan_Memory_Foam_Shelter.md"},
    ]
    synthetic = {"clusters": fixture["clusters"]}
    result = candidate_signals(synthetic, {"plans": rows})
    assert [item[0] for item in result["npc-memory"]] == ["B"]
    assert classify("Food pipeline cooking", ["food pipeline", "cooking"])
    valid = "# Duplicate-search receipt — Plan A\n\nPlan ID: `A`\n"
    assert validate_receipt_content("fixture", "A", "receipt.md", valid) == []
    assert validate_receipt_content("fixture", "A", "receipt.md", "# Wrong heading\nPlan ID: `A`\n")
    assert validate_receipt_content("fixture", "A", "receipt.md", "# Duplicate-search receipt\nPlan ID: `B`\n")
    print("capability cluster self-test: PASS")


def write_if_changed(path: Path, content: str) -> bool:
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write the generated Markdown report")
    parser.add_argument("--check", action="store_true", help="fail if the generated report is stale")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        self_test()
        return 0
    try:
        source, register = load_json(SOURCE), load_json(REGISTER)
    except (OSError, json.JSONDecodeError) as error:
        print(f"cannot read E1E inputs: {error}", file=sys.stderr)
        return 2
    errors = validate(ROOT, source, register)
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    content = markdown(source, register)
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            print("capability cluster report drift detected; run with --write", file=sys.stderr)
            return 1
    if args.write or not args.check:
        write_if_changed(OUTPUT, content)
    print(f"capability clusters: {len(source['clusters'])} reviewed; plan statuses unchanged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
