#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""
generate-keyboard-map.py — Generates or validates docs/ui/KEYBOARD.md from the
canonical input action contract in src/Host/AshfallInputActions.cs and project.godot.
Enforces that keyboard documentation is machine-generated and cannot drift.
"""

import sys
import os
import re

def main():
    check_mode = "--check" in sys.argv

    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    actions_file = os.path.join(repo_root, "src", "Host", "AshfallInputActions.cs")
    godot_file = os.path.join(repo_root, "project.godot")
    output_file = os.path.join(repo_root, "docs", "ui", "KEYBOARD.md")

    if not os.path.exists(actions_file):
        print(f"ERROR: {actions_file} not found", file=sys.stderr)
        sys.exit(1)

    with open(actions_file, "r", encoding="utf-8") as f:
        actions_content = f.read()

    # Parse CanonicalDefaults
    canonical_defaults = {}
    # Parse constants
    constants = {}
    for m in re.finditer(r'public const string\s+([A-Za-z0-9_]+)\s*=\s*"([^"]+)";', actions_content):
        constants[m.group(1)] = m.group(2)

    defaults_match = re.search(r'CanonicalDefaults\s*=\s*new Dictionary<string, Key>\s*\{(?P<entries>.*?)\};', actions_content, re.DOTALL)
    if defaults_match:
        for m in re.finditer(r'\{\s*([A-Za-z0-9_]+)\s*,\s*Key\.([A-Za-z0-9_]+)\s*\}', defaults_match.group("entries")):
            canonical_defaults[m.group(1)] = m.group(2)

    # Parse Contract table
    contracts = []
    contract_match = re.search(r'Contract\s*=\s*new\[\]\s*\{(?P<entries>.*?)\};', actions_content, re.DOTALL)
    if contract_match:
        for m in re.finditer(r'new\s+InputActionContract\s*\(\s*([A-Za-z0-9_]+)\s*,\s*InputScope\.([A-Za-z0-9_]+)\s*,\s*("[^"]*"|null)\s*,\s*(true|false)\s*\)', contract_match.group("entries")):
            action_const = m.group(1)
            scope = m.group(2)
            route = m.group(3).strip('"') if m.group(3) != "null" else "—"
            rebindable = "Yes" if m.group(4) == "true" else "No"
            contracts.append({
                "const": action_const,
                "action": constants.get(action_const, action_const),
                "scope": scope,
                "route": route,
                "rebindable": rebindable
            })

    # Friendly Key Names
    key_display = {
        "Escape": "Escape",
        "Enter": "Enter / Return",
        "Tab": "Tab",
        "Up": "Up Arrow",
        "Down": "Down Arrow",
        "Left": "Left Arrow",
        "Right": "Right Arrow",
        "Key1": "1",
        "Key2": "2",
        "Key3": "3",
        "Key4": "4",
        "Key5": "5",
        "F1": "F1",
        "F2": "F2"
    }

    # Joypad mapping summary
    joypad_map = {
        "Close": "JoyButton.B (Back / Cancel)",
        "Confirm": "JoyButton.A (Accept / Select)",
        "NextTab": "JoyButton.RightShoulder (RB / R1)",
        "NavUp": "JoyButton.DpadUp / Left Stick Up",
        "NavDown": "JoyButton.DpadDown / Left Stick Down",
        "NavLeft": "JoyButton.DpadLeft / Left Stick Left",
        "NavRight": "JoyButton.DpadRight / Left Stick Right",
        "Journal": "JoyButton.Y (Journal / Codex)",
        "Help": "JoyButton.Back (Help / Tutorial)"
    }

    lines = []
    lines.append("# ASHFALL — Authoritative Keyboard & Controller Map")
    lines.append("")
    lines.append("> **Generated Document**: Do not edit manually. Generated by `scripts/ci/generate-keyboard-map.py`")
    lines.append("> from canonical contracts in `src/Host/AshfallInputActions.cs` and `project.godot`.")
    lines.append("")
    lines.append("## Canonical Action Registry")
    lines.append("")
    lines.append("| Action | Scope | Default Key | Controller / Joypad | Target Route | Rebindable |")
    lines.append("|---|---|---|---|---|---|")

    for c in contracts:
        c_const = c["const"]
        def_key_raw = canonical_defaults.get(c_const, "None")
        def_key = key_display.get(def_key_raw, def_key_raw)
        joypad = joypad_map.get(c_const, "—")
        lines.append(f"| `{c['action']}` | `{c['scope']}` | `{def_key}` | {joypad} | `{c['route']}` | {c['rebindable']} |")

    lines.append("")
    lines.append("## Focus & Navigation Contracts")
    lines.append("")
    lines.append("- **Initial Focus**: Every overlay open routes through `AshfallFocusPolicy.OpenWithFocus`.")
    lines.append("- **Focus Trapping**: Active overlays trap `Tab` / `Shift+Tab` within their interactive child controls.")
    lines.append("- **Spatial Navigation**: Directional navigation (`Up`, `Down`, `Left`, `Right`) is handled by `AshfallFocusNavigator.MoveDirection`.")
    lines.append("- **Focus Restoration**: Dismissing an overlay via `Escape` or close button cleanly restores focus to the invoking opener.")
    lines.append("- **Safe Mode**: Holding `Shift` during application startup boots into safe mode, bypassing custom user keybindings.")

    generated = "\n".join(lines) + "\n"

    if check_mode:
        if not os.path.exists(output_file):
            print(f"ERROR: {output_file} does not exist. Run python3 scripts/ci/generate-keyboard-map.py to generate it.", file=sys.stderr)
            sys.exit(1)
        with open(output_file, "r", encoding="utf-8") as f:
            existing = f.read()
        if existing != generated:
            print(f"ERROR: {output_file} is out of date with AshfallInputActions.cs contract! Run python3 scripts/ci/generate-keyboard-map.py to update it.", file=sys.stderr)
            sys.exit(1)
        print("KEYBOARD.md check PASS: Up to date with canonical contracts.")
        sys.exit(0)
    else:
        os.makedirs(os.path.dirname(output_file), exist_ok=True)
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(generated)
        print(f"Wrote generated keyboard map to {output_file}")

if __name__ == "__main__":
    main()
