import json

file_path = "/home/robertsrff/Music/Atomic_War_Straving_Survival/Atomic War/Assets/StreamingAssets/Data/micro_locations.json"
with open(file_path, "r") as f:
    data = json.load(f)

replacements = {
    "Melted candle stubs sit inside cut tin cans around a bent road marker. A photograph has been removed, but one corner remains beneath a stone. The wax has pooled and frozen in grey discs.": "Melted tallow stubs sit inside rusted rationing tins around a bent highway marker. A photograph was torn away, leaving only a bloodstained corner pinned beneath a stone. The wax has frozen into pale, grey discs.",
    "A logistics vehicle has crushed its cab into the ditch. Torn inventory tags cling to the rear doors. Several crates were removed long before you arrived, but one has split open on the road.": "A military logistics rig lies crushed in the frozen ditch, its windshield shattered outward. Torn radiation warning tags cling to the twisted rear doors. The cargo area was scavenged long ago, but one crate lies split open in the frost.",
    "The doors are frozen open. Frost films the inside of the windows. A child's shoe lies upright on one seat beneath a luggage rack. The heating vents are clogged with ash.": "The transit doors are frozen wide open, letting the ash-laden wind howl through the cabin. A child's single shoe sits upright beneath a luggage rack. The windows are obscured by thick, greasy frost on the inside.",
    "A shallow mound has been reinforced with stones. A name is scratched into a broken plank with a date and nothing else. The earth is frozen hard.": "A shallow mound of frozen earth, hastily reinforced with chunks of shattered concrete. A name is violently gouged into a piece of broken siding, along with a date from the first winter of the ashfall.",
    "One span lies in the river at an angle. A vehicle is wedged against the concrete below, only its rear half above the waterline. The current has carved a channel through the debris.": "A colossal span of reinforced concrete leans broken into the black, freezing river. A transport vehicle is wedged violently against the submerged rebar, its rear doors hanging open just above the roaring current.",
    "Blankets have been pushed deep into a concrete culvert. A warning is scratched into the wall where rainwater cannot wash it away. Something has been living here recently.": "Rags and irradiated blankets have been pushed deep into this dark concrete culvert. A desperate warning is gouged into the wall just beyond the reach of the freezing rain. The smell of copper and unwashed bodies lingers.",
    "A wheelset has sunk into the ballast. The maintenance ledger is still clipped beside the door of a derailed freight car. The last pages were written in different handwriting.": "Rusted wheelsets have sunk deep into the irradiated ballast. A maintenance ledger hangs from the side of a derailed freight car, the final pages written in frantic, shaky handwriting before ending abruptly.",
    "Ear tags glitter among the weeds. The bodies were moved into a rough line before whoever did the work stopped. The smell is long gone, but the contamination lingers.": "Plastic ear tags flutter in the ash-wind among the dead weeds. Massive, bloated bodies of livestock were dragged into a rough trench, but the grave diggers abandoned the work. The Geiger counter stutters nervously here.",
    "Most of the panes are gone. Dry seed trays remain labeled beneath the benches. One cabinet is still sealed against moisture. The door has been forced once but not fully opened.": "Shattered glass crunches underfoot in this ruined greenhouse. Desiccated seed trays lie beneath the rusted benches. In the corner, a heavy steel cabinet remains sealed—someone tried to pry it open with a crowbar, but gave up or died trying.",
    "The earth is glassy along one side of the crater. A torn harness and fragments of stamped metal are half-buried in the frozen soil. The ground sounds hollow when you step near the edge.": "The blast fused the earth into dark, jagged glass along one side of the massive crater. A torn military harness and scorched metal fragments are fused into the soil. Stepping near the rim, the ground sounds terrifyingly hollow.",
    "A large cooking pot is frozen to the stand. Ladles hang from wire hooks. Ration marks have been scratched into the serving table. The fire pit is cold and clean-swept.": "A massive cast-iron cooking pot is frozen solid to its metal stand. Bent ladles hang from rusted wire hooks. Hundreds of desperate tally marks are gouged into the serving table, tracking rations that eventually ran out.",
    "The casing is open and two cables have been cut cleanly. Someone marked the fuel mixture on the frame in grease pencil. The engine block is cold but intact.": "The heavy generator casing is wrenched open, its primary power cables severed with surgical precision. A frantic fuel mixture ratio is scrawled in grease pencil on the frame. The heavy block is dead, but it could be salvaged.",
    "Candles have burned down inside a rusted food tin. Small offerings sit beneath a strip of cloth tied to the guardrail. The cloth is faded but carefully knotted.": "Tallow candles have burned down to stubs inside a rusted ration tin. Desperate little offerings—screws, shiny pebbles, a bullet—sit beneath a faded cloth carefully knotted around the twisted guardrail.",
    "The weather seal has cracked but the stencil is still readable. Someone tried the lock with a pry bar and gave up. The stencil reads CIVIL DEFENSE — EMERGENCY RATION CACHE.": "The rubber weather seal has cracked in the bitter cold, but the faded stencil is undeniable. Deep gouges show where someone tried to pry the heavy lock before abandoning it. It reads: CIVIL DEFENSE — EMERGENCY RATION CACHE.",
    "The optics mount still points toward the crossing. Grid references are written on the inside wall beside dates that stop abruptly. A spent cartridge sits on the windowsill.": "A heavy optics mount still points silently toward the desolate crossing below. Frantic grid references and kill-counts are scrawled on the concrete wall, stopping abruptly mid-sentence. A single spent sniper cartridge sits on the frozen windowsill.",
    "Traffic arrows were repainted twice in different colors. A body lies behind the barrier beside a box that was opened from the road-facing side. The sandbags have frozen solid.": "Traffic arrows were repainted twice in different faction colors, marking shifting territories. A mummified corpse lies slumped behind the barrier, clutching a rusted lockbox. The sandbags have frozen into a solid, bullet-pocked wall.",
    "The blind has collapsed on one side. A thermos, empty cartridge box, and a journal wrapped in cloth remain under the bench. The journal is damp but legible.": "Half of the camouflage blind has collapsed under the weight of radioactive ash. An empty thermos, scattered brass casings, and a cloth-wrapped journal lie abandoned under the bench. The damp pages chronicle a hunt that went terribly wrong.",
    "The mast has folded halfway down the hill. One feed line is intact and disappears into a locked cabinet at the base. The cabinet has been pried but not opened.": "The towering mast has buckled, its twisted steel groaning in the wind. A single intact feed line snakes into a heavy, locked utility cabinet at the base. The metal door is scarred with deep claw marks.",
    "Concrete barriers are blackened on the shelter-facing side. A logbook is pinned beneath a fallen chair where rain has not reached it. The checkpoint identity plate is missing.": "Heavy concrete barriers are scorched black on the side facing the bunker, suggesting whatever attacked came from within. A blood-spattered logbook is pinned beneath a collapsed steel chair. The faction identity plate has been violently torn away.",
    "The tent fabric has collapsed under snow. Inside, cups are nested together beside a folded child's drawing kept dry inside a plastic sleeve. The zipper is frozen shut.": "The military-grade fabric has collapsed under the weight of grey snow. Inside, nested tin cups sit beside a child's crayon drawing, meticulously preserved in a plastic sleeve. The tent's zipper is frozen shut from the inside.",
    "Triage numbers are written on strips of cardboard. Empty saline bags hang from a cable. The medicine cabinet has been searched unevenly — some shelves are bare, others untouched.": "Desperate triage categories are scrawled in blood on torn cardboard strips. Empty, frozen saline bags hang from a rusted IV cable. The medicine cabinet was ransacked in a panic—leaving some shelves completely bare while ignoring others entirely.",
    "One wing is embedded in hard soil. The casing has been opened once, but the flight-control compartment is still sealed. Battery acid has stained the ground beneath it.": "One shattered wing is driven deep into the frozen earth. The outer casing was ripped open by scavengers, but the armored flight-control compartment remains sealed. Corrosive battery acid has burned a dark, hissing stain into the soil.",
    "Two containers are buried beneath a sheet of corrugated metal. A route sketch has been scratched into one lid with a nail. The containers are heavy and sealed.": "Two military drums are half-buried beneath a rusted sheet of corrugated metal. A desperate route map to a safe zone has been scratched into one lid with a nail. The drums are heavy, their tamper-seals unbroken.",
    "A metal cup is tied to a hand pump with wire. Mineral staining marks the basin. Someone has written a date beside the word for 'safe' in charcoal. The pump handle moves freely.": "A dented tin cup is bound to the rusted hand pump with frayed wire. Heavy, unnatural mineral staining marks the concrete basin. Someone wrote 'SAFE' in charcoal, alongside a date from five years ago. The pump handle still groans when moved.",
    "The parachute is tangled in dead trees. The crate markings identify a destination several kilometres from where it actually landed. The crate is intact but the seal is broken.": "The faded military parachute is hopelessly tangled in the black, petrified branches of dead trees. The stenciled coordinates indicate it drifted miles off course. The reinforced crate is intact, but the heavy locking seal has been severed."
}

for item in data.get("encounters", []):
    if "description" in item and item["description"] in replacements:
        item["description"] = replacements[item["description"]]

with open(file_path, "w") as f:
    json.dump(data, f, indent=2)

print("Patch applied to micro_locations.json")
