// SPDX-License-Identifier: MIT
// ASHFALL: Shelter interior decor system (Plan 12C — White Space 3).
//
// Per-room decor placements, deterministic localized morale modifier.
// Engine-agnostic: plain serializable DTOs, no ISeededRng, save/round-trip
// safe. The host wires this system into the room-view UI (golden snapshots
// untouched) and the morale tick (NeedsSystem.Modify per survivor per
// tick with the modifier returned by GetRoomMoraleDelta).
//
// The system never mutates ShelterAssignmentSystem, NeedsSystem, or
// MemorialSystem. It exposes:
//   - Assign / Remove / GetSlot / ListSlots per (roomId, slotId, itemId)
//   - GetRoomMoraleDelta(roomId) for the localized morale readout
//   - OnDecorChanged event the host can subscribe to for UI dirty paint
//   - CaptureState / RestoreState round-trip via SaveStore<T> envelope
//
// Memorial bridge: when a MemorialEntry is committed with a known
// HeirloomItemId belonging to the canon plaque item set, ResolvePlaqueSlot
// returns the slot assignment the host should auto-publish to the wall.

using System;
using System.Collections.Generic;
#pragma warning disable CS8618

namespace Ashfall.Core.Shelter
{
    [Serializable]
    public class ShelterDecorPlacement
    {
        /// <summary>Room where the decor is mounted. Free-text, matches a ShelterRoom.RoomId in the host.</summary>
        public string RoomId = string.Empty;
        /// <summary>Logical slot id within the room, e.g. "north_wall", "south_pegs". The host decides the slot vocabulary by calling Assign with the slot id it wants to populate.</summary>
        public string SlotId = string.Empty;
        /// <summary>Canonical item id (item_decor_* from items.json). When empty the slot is empty.</summary>
        public string ItemId = string.Empty;
        /// <summary>Day the placement was installed. Captured for chronology + future memorial hooks.</summary>
        public int DayInstalled;
        /// <summary>When true the placement was auto-generated by memorial (Plan 09 9C cross-link), True means it is itself the memorial plaque for the named survivor.</summary>
        public bool IsMemorialPlaque;
        /// <summary>If IsMemorialPlaque is true, this is the survivor the plaque commemorates.</summary>
        public string MemorialSurvivorId = string.Empty;
        /// <summary>If IsMemorialPlaque is true, this is the source MemorialEntry.HeirloomItemId the plaque replaced.</summary>
        public string PlaqueSourceHeirloomId = string.Empty;
    }

    [Serializable]
    public class ShelterDecorState
    {
        public const string SystemId = "shelter_decor";

        public string systemId = SystemId;
        public string Checksum = string.Empty;
        public List<ShelterDecorPlacement> Placements = new List<ShelterDecorPlacement>();

        public ShelterDecorStateCapture Capture() => new ShelterDecorStateCapture
        {
            systemId = systemId,
            Placements = new List<ShelterDecorPlacement>(Placements ?? new List<ShelterDecorPlacement>())
        };

        public void RestoreInto(ShelterDecorState other)
        {
            systemId = SystemId;
            Placements = other?.Placements != null ? new List<ShelterDecorPlacement>(other.Placements) : new List<ShelterDecorPlacement>();
        }
    }

    /// <summary>Alias to keep save-envelope wiring compatible with SaveStore&lt;T&gt;.</summary>
    [Serializable]
    public sealed class ShelterDecorStateCapture : ShelterDecorState { }

    /// <summary>
    /// Engine-agnostic decor placement registry. Owner of the canonical
    /// (roomId, slotId) -> itemId mapping for the application. Configure
    /// the decor items via items.json (id prefix <c>item_decor_</c>) and
    /// their localized morale modifiers via the catalogued
    /// <see cref="ShelterDecorItemModifier"/> map the host wires.
    /// </summary>
    public sealed class ShelterDecorSystem
    {
        public const string SystemId = "shelter_decor";
        /// <summary>"Memorial plaque" canonical item id prefix (Plan 12C + Plan 09 9C cross-link).</summary>
        public const string MemorialPlaquePrefix = "item_decor_memorial_plaque";

        private readonly ShelterDecorState _state = new ShelterDecorState();
        private readonly Dictionary<string, ShelterDecorItemModifier> _itemModifiers =
            new Dictionary<string, ShelterDecorItemModifier>(StringComparer.Ordinal);

        public ShelterDecorState State => _state;
        public event Action<ShelterDecorPlacement>? OnDecorChanged;
        public event Action? OnStateChanged;

        public IReadOnlyDictionary<string, ShelterDecorItemModifier> ItemModifiers => _itemModifiers;

        /// <summary>
        /// Register or replace an item's localized morale modifier. The host
        /// pulls modifiers from items.json (or any declarative source) at
        /// boot and forwards them here. Idempotent; replacing a modifier
        /// does NOT re-trigger OnDecorChanged because the change is at the
        /// catalog level, not at a placement level.
        /// </summary>
        public void RegisterItemModifier(ShelterDecorItemModifier modifier)
        {
            if (modifier == null || string.IsNullOrEmpty(modifier.ItemId)) return;
            _itemModifiers[modifier.ItemId] = modifier;
        }

        public ShelterDecorItemModifier? GetItemModifier(string itemId)
        {
            if (string.IsNullOrEmpty(itemId)) return null;
            return _itemModifiers.TryGetValue(itemId, out var m) ? m : null;
        }

        /// <summary>
        /// Assign (or replace) the decor item at (roomId, slotId). Returns
        /// true on placement, false on rejected inputs. Empty ItemId is
        /// the unassign sentinel. The host uses Empty ItemId + same
        /// (roomId, slotId) to remove a placement cleanly.
        /// </summary>
        public bool Assign(string roomId, string slotId, string itemId, int dayInstalled, bool isMemorialPlaque = false, string memorialSurvivorId = "", string plaqueSourceHeirloomId = "")
        {
            if (string.IsNullOrEmpty(roomId) || string.IsNullOrEmpty(slotId)) return false;

            var placement = new ShelterDecorPlacement
            {
                RoomId = roomId,
                SlotId = slotId,
                ItemId = itemId ?? string.Empty,
                DayInstalled = dayInstalled,
                IsMemorialPlaque = isMemorialPlaque,
                MemorialSurvivorId = memorialSurvivorId ?? string.Empty,
                PlaqueSourceHeirloomId = plaqueSourceHeirloomId ?? string.Empty
            };
            _state.Placements.RemoveAll(p =>
                string.Equals(p.RoomId, roomId, StringComparison.Ordinal)
                && string.Equals(p.SlotId, slotId, StringComparison.Ordinal));
            _state.Placements.Add(placement);
            OnDecorChanged?.Invoke(placement);
            OnStateChanged?.Invoke();
            return true;
        }

        /// <summary>Convenience: Remove the placement at (roomId, slotId). Returns true if a placement was removed.</summary>
        public bool Remove(string roomId, string slotId)
        {
            if (string.IsNullOrEmpty(roomId) || string.IsNullOrEmpty(slotId)) return false;
            int before = _state.Placements.Count;
            _state.Placements.RemoveAll(p =>
                string.Equals(p.RoomId, roomId, StringComparison.Ordinal)
                && string.Equals(p.SlotId, slotId, StringComparison.Ordinal));
            if (_state.Placements.Count == before) return false;
            OnStateChanged?.Invoke();
            return true;
        }

        public ShelterDecorPlacement? GetSlot(string roomId, string slotId)
        {
            if (string.IsNullOrEmpty(roomId) || string.IsNullOrEmpty(slotId)) return null;
            for (int i = 0; i < _state.Placements.Count; i++)
            {
                var p = _state.Placements[i];
                if (string.Equals(p.RoomId, roomId, StringComparison.Ordinal)
                    && string.Equals(p.SlotId, slotId, StringComparison.Ordinal))
                    return p;
            }
            return null;
        }

        /// <summary>All placements in a single room, ordinal-ordered.</summary>
        public List<ShelterDecorPlacement> ListRoomPlacements(string roomId)
        {
            var list = new List<ShelterDecorPlacement>();
            if (string.IsNullOrEmpty(roomId)) return list;
            for (int i = 0; i < _state.Placements.Count; i++)
                if (string.Equals(_state.Placements[i].RoomId, roomId, StringComparison.Ordinal))
                    list.Add(_state.Placements[i]);
            list.Sort((a, b) => string.CompareOrdinal(a.SlotId, b.SlotId));
            return list;
        }

        /// <summary>
        /// Sum of all decor modifiers currently mounted in a room. The
        /// host applies this to <c>NeedsSystem.Modify(survivorId, Morale, delta)</c>
        /// for each occupant during the morale tick.
        /// </summary>
        public float GetRoomMoraleDelta(string roomId)
        {
            float sum = 0f;
            var placements = ListRoomPlacements(roomId);
            for (int i = 0; i < placements.Count; i++)
            {
                var p = placements[i];
                if (string.IsNullOrEmpty(p.ItemId)) continue;
                var mod = GetItemModifier(p.ItemId);
                if (mod == null) continue;
                sum += mod.LocalizedMoraleDelta;
            }
            return sum;
        }

        /// <summary>
        /// Resolve a memorial plaque slot from a MemorialEntry. The plaque
        /// is mounted at the (default) memorial wall slot of the room
        /// already designated as the residence of the heirloom recipient.
        /// When the recipient has no assigned room the host may pass
        /// "<default_room>" to mount the plaque in the lobby.
        ///
        /// The returned <see cref="ShelterDecorPlacement"/> has ItemId
        /// looked up via <see cref="ResolvePlaqueItemId"/>. The host should
        /// call <see cref="Assign"/> on it.
        /// </summary>
        public ShelterDecorPlacement? ResolvePlaqueSlot(string memorialSurvivorId, string heirloomItemId, string memorialWallRoom, string plaqueSlotId, int dayInstalled)
        {
            var plaqueItemId = ResolvePlaqueItemId(heirloomItemId);
            if (string.IsNullOrEmpty(plaqueItemId)) return null;
            return new ShelterDecorPlacement
            {
                RoomId = memorialWallRoom ?? string.Empty,
                SlotId = plaqueSlotId ?? string.Empty,
                ItemId = plaqueItemId,
                DayInstalled = dayInstalled,
                IsMemorialPlaque = true,
                MemorialSurvivorId = memorialSurvivorId ?? string.Empty,
                PlaqueSourceHeirloomId = heirloomItemId ?? string.Empty
            };
        }

        /// <summary>
        /// Convert a MemorialEntry.HeirloomItemId into the canonical
        /// plaque item id the decor catalog ships. The mapping is:
        ///   "item_personal_keepsake_&lt;survivor&gt;" or any "personal_keepsake_*"
        ///   -> the matching "item_decor_memorial_plaque" entry by category
        /// The host may also pass any source id and get the generic plaque
        /// as a fallback so the slot is never empty.
        /// </summary>
        public string ResolvePlaqueItemId(string heirloomItemId)
        {
            if (string.IsNullOrEmpty(heirloomItemId)) return string.Empty;
            // Match the host's preferred canonical id for the recipient's
            // heirloom kind. Falls back to a single global generic plaque.
            string kindTag = ExtractHeirloomKind(heirloomItemId);
            if (!string.IsNullOrEmpty(kindTag)
                && _itemModifiers.TryGetValue(MemorialPlaquePrefix + "_" + kindTag, out var specific))
            {
                return MemorialPlaquePrefix + "_" + kindTag;
            }
            // Fallback to generic plaque if registered.
            if (_itemModifiers.ContainsKey(MemorialPlaquePrefix + "_generic"))
                return MemorialPlaquePrefix + "_generic";
            // Cold fallback: if the catalog never registered a generic
            // plaque, return the empty string so the host can surface a
            // missing-plaque UI affordance rather than silently choosing
            // an unknown item.
            return string.Empty;
        }

        private static string ExtractHeirloomKind(string heirloomItemId)
        {
            if (string.IsNullOrEmpty(heirloomItemId)) return string.Empty;
            // Convention: heirloom ids published by enrollment & final-wish
            // systems carry the survivor's name + a kind tag. The plan-12C
            // shape is "item_personal_keepsake_{survivor}_{kind}"; we extract
            // the trailing kind segment. Other shapes are intentionally
            // not accommodated \u2014 callers ship canonical ids.
            int idx = heirloomItemId.LastIndexOf('_');
            if (idx < 0 || idx == heirloomItemId.Length - 1) return string.Empty;
            string tail = heirloomItemId.Substring(idx + 1);
            return string.Equals(tail, "default", StringComparison.OrdinalIgnoreCase)
                ? string.Empty
                : tail;
        }

        public ShelterDecorStateCapture CaptureState() => _state.Capture();

        public void RestoreState(ShelterDecorStateCapture saved)
        {
            if (saved == null) return;
            _state.RestoreInto(saved);
            OnStateChanged?.Invoke();
        }
    }

    /// <summary>
    /// Declarative item modifier for a decor item. Authoritative values
    /// live in items.json (canonical item_decor_* ids). The host
    /// extracts the modifier from items via the mod_schema pipeline and
    /// registers it on the system at boot.
    /// </summary>
    [Serializable]
    public class ShelterDecorItemModifier
    {
        public string ItemId = string.Empty;
        /// <summary>Localized morale bonus per tick while survivor sits in the decorated room.</summary>
        public float LocalizedMoraleDelta;
        /// <summary>Optional display category the host UI may use for sorting (poster/plaque/trophy).</summary>
        public string Category = string.Empty;
        /// <summary>When true, the host may stack the modifier multiplicatively; by default additive.</summary>
        public bool StackMultiplicatively;
    }
}
