//! Port of `tools/gotools/pkg/agentsync/agentsync.go`.
//!
//! `sync-agents` makes each of the 13 client rulebooks a relative symlink to
//! the canonical `AGENTS.md`, or (with `--check`) reports drift without
//! touching anything. It fails if `AGENTS.md` is missing or lacks the
//! non-negotiable-rules marker.
//!
//! Parity note: Go stores the target clients in a `map[string]string`, so its
//! `updated` order and the generated report's bullet order are non-deterministic
//! between runs. This port iterates the same set in a fixed sorted order so the
//! output is reproducible; the membership and every per-file decision match.

use crate::gotime;
use std::path::{Path, PathBuf};

/// Canonical client rulebooks and their (unused-by-logic) headings, mirroring
/// Go's `TargetClients`. Sorted here so iteration is deterministic.
pub const TARGET_CLIENTS: [(&str, &str); 13] = [
    (".clinerules", "ASHFALL PROJECT — Cline Rules"),
    (".cursorrules", "ASHFALL PROJECT — Cursor Rules"),
    (".windsurfrules", "ASHFALL PROJECT — Windsurf Rules"),
    ("ANTIGRAVITY.md", "ASHFALL PROJECT — ANTIGRAVITY Instructions"),
    ("CLAUDE.md", "CLAUDE CODE INSTRUCTIONS — ASHFALL PROJECT"),
    ("CODEX.md", "ASHFALL PROJECT — CODEX Instructions"),
    ("CRUSH.md", "ASHFALL PROJECT — CRUSH Instructions"),
    ("GEMINI.md", "ASHFALL PROJECT — GEMINI Instructions"),
    ("GOOSE.md", "ASHFALL PROJECT — GOOSE Instructions"),
    ("MIMOCODE.md", "ASHFALL PROJECT — MIMOCODE Instructions"),
    ("OPENSETUP.md", "ASHFALL PROJECT — OPENSETUP Instructions"),
    ("QWEN.md", "ASHFALL PROJECT — QWEN Instructions"),
    ("VIBE.md", "ASHFALL PROJECT — VIBE Instructions"),
];

/// Marker that must be present in the canonical `AGENTS.md`.
pub const NON_NEGOTIABLE_MARKER: &str = "## READ THIS FIRST — NON-NEGOTIABLE RULES";

/// Port of `SyncAgentRulebooks`. Returns `(in_sync, updated, error)`.
pub fn sync_agent_rulebooks(
    repo_root: &str,
    check_only: bool,
) -> Result<(bool, Vec<String>), String> {
    let canonical_path = Path::new(repo_root).join("AGENTS.md");
    let content = std::fs::read_to_string(&canonical_path)
        .map_err(|e| format!("canonical AGENTS.md not found: {}", e))?;
    if !content.contains(NON_NEGOTIABLE_MARKER) {
        return Err(format!(
            "marker {:?} not found in AGENTS.md",
            NON_NEGOTIABLE_MARKER
        ));
    }

    let today = {
        let now = gotime::now_utc_rfc3339();
        now[..10.min(now.len())].to_string()
    };

    let mut drifted: Vec<String> = Vec::new();
    let mut updated: Vec<String> = Vec::new();

    for (filename, _) in TARGET_CLIENTS {
        let target_path = Path::new(repo_root).join(filename);
        let link = std::fs::read_link(&target_path)
            .map(|p| p.to_string_lossy().into_owned())
            .ok();
        let existing = std::fs::read_to_string(&target_path).ok();

        let in_sync =
            link.as_deref() == Some("AGENTS.md") && existing.as_deref() == Some(content.as_str());
        if in_sync {
            continue;
        }
        drifted.push(filename.to_string());
        if !check_only {
            // Replace the entry atomically; never write through a symlink.
            let temporary = PathBuf::from(format!("{}.sync-link", target_path.to_string_lossy()));
            let _ = std::fs::remove_file(&temporary);
            if let Err(e) = std::os::unix::fs::symlink("AGENTS.md", &temporary) {
                return Err(format!(
                    "failed to create {}: {}",
                    temporary.to_string_lossy(),
                    e
                ));
            }
            if let Err(e) = std::fs::rename(&temporary, &target_path) {
                let _ = std::fs::remove_file(&temporary);
                return Err(format!("failed to replace {}: {}", filename, e));
            }
            updated.push(filename.to_string());
        }
    }

    if !check_only {
        let report_path = Path::new(repo_root)
            .join("docs")
            .join("agents")
            .join("AGENTS_SYNC_REPORT.md");
        if let Some(parent) = report_path.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        let mut report = String::new();
        report.push_str(&format!(
            "# Agent Rulebooks Synchronization Report\nGenerated: {}\n\n",
            today
        ));
        report.push_str("All client rulebooks are relative symlinks to canonical `AGENTS.md`, generated by `ashfall-dev sync-agents`. Readers receive the complete rules through one authority:\n");
        for (filename, _) in TARGET_CLIENTS {
            report.push_str(&format!("- [x] `{}`\n", filename));
        }
        let _ = std::fs::write(&report_path, report);
    }

    Ok((drifted.is_empty(), updated))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn tmpdir(tag: &str) -> PathBuf {
        let base = std::env::temp_dir().join(format!(
            "ashfall-rstools-agentsync-{}-{}",
            tag,
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&base);
        fs::create_dir_all(&base).unwrap();
        base
    }

    #[test]
    fn missing_canonical_file_errors() {
        let root = tmpdir("missing");
        let err = sync_agent_rulebooks(&root.to_string_lossy(), true).unwrap_err();
        assert!(err.contains("canonical AGENTS.md not found"), "{err}");
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn missing_marker_errors() {
        let root = tmpdir("marker");
        fs::write(root.join("AGENTS.md"), "# no marker").unwrap();
        let err = sync_agent_rulebooks(&root.to_string_lossy(), true).unwrap_err();
        assert!(err.contains("not found in AGENTS.md"), "{err}");
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn check_reports_drift_then_apply_links_and_report() {
        let root = tmpdir("apply");
        let canonical = format!("# AGENTS\n{}\nbody\n", NON_NEGOTIABLE_MARKER);
        fs::write(root.join("AGENTS.md"), &canonical).unwrap();

        // Nothing linked yet: every client drifts.
        let (ok, updated) = sync_agent_rulebooks(&root.to_string_lossy(), true).unwrap();
        assert!(!ok);
        assert!(updated.is_empty());

        let (ok, updated) = sync_agent_rulebooks(&root.to_string_lossy(), false).unwrap();
        // Go returns `ok == len(drifted) == 0`; a run that had to repair links
        // reports the drift it found, exactly as the Go original does.
        assert!(!ok, "a repairing run reports the drift it found");
        assert_eq!(updated.len(), 13);
        assert!(root.join("docs/agents/AGENTS_SYNC_REPORT.md").exists());
        for (filename, _) in TARGET_CLIENTS {
            let link = fs::read_link(root.join(filename)).unwrap();
            assert_eq!(link.to_string_lossy(), "AGENTS.md", "{filename}");
        }

        // Second run: already in sync, nothing updated.
        let (ok, updated) = sync_agent_rulebooks(&root.to_string_lossy(), false).unwrap();
        assert!(ok);
        assert!(updated.is_empty());
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn regular_file_instead_of_symlink_is_drift() {
        let root = tmpdir("regular");
        let canonical = format!("# AGENTS\n{}\n", NON_NEGOTIABLE_MARKER);
        fs::write(root.join("AGENTS.md"), &canonical).unwrap();
        for (filename, _) in TARGET_CLIENTS {
            fs::write(root.join(filename), &canonical).unwrap();
        }
        let (ok, _) = sync_agent_rulebooks(&root.to_string_lossy(), true).unwrap();
        assert!(!ok, "a copied regular file is not a symlink and must drift");
        let _ = fs::remove_dir_all(&root);
    }
}