using System.Collections.Generic;
using System.IO;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;
using AtomicWar._Game.Editor;

namespace AtomicWar.Tests.EditMode
{
    [TestFixture]
    public class BuildPipelineValidationTests
    {
        [Test]
        public void ValidateData_WithValidJson_PassesDataValidationGate()
        {
            List<string> errors = JsonDataImporter.ValidateAll();
            Assert.That(errors, Is.Not.Null);
            Assert.That(errors.Count, Is.EqualTo(0), $"Master JSON data should have zero validation errors, but found: {string.Join("; ", errors)}");
        }

        /// <summary>
        /// Runs a real player build inside the EditMode suite: 13.9s of the 24s the
        /// other ~1830 tests share between them. (A run's wall time is dominated by
        /// editor startup and domain reload, not by this — skipping it shortens the
        /// test phase, not the run.) Categorised so a local iteration loop can drop it
        /// with <c>-testCategory "!SlowBuild"</c>; CI runs the full set, so the
        /// pipeline gate keeps its coverage.
        /// </summary>
        [Test]
        [Category("SlowBuild")]
        public void BuildPipeline_ExecutesDataValidationGate_AndOutputsBuildLog()
        {
            // PerformBuildPipeline may Refresh the AssetDatabase / invoke player builds.
            // In concurrent batchmode that can emit engine Asserts such as
            // currentFileSystemTime.ticks != 0 (Temp/FSTimeGet-*). Those are
            // environment noise, not pipeline logic failures — ignore them so the
            // suite still verifies the validation gate wrote build_log.txt.
            bool prevIgnore = LogAssert.ignoreFailingMessages;
            LogAssert.ignoreFailingMessages = true;
            try
            {
                BuildScript.PerformBuildPipeline();
            }
            finally
            {
                LogAssert.ignoreFailingMessages = prevIgnore;
            }

            Assert.That(File.Exists(BuildScript.LogFilePath), Is.True, "build_log.txt must be generated by BuildScript pipeline.");
            string logText = File.ReadAllText(BuildScript.LogFilePath);
            Assert.That(logText, Does.Contain("STEP 1: JSON DATA VALIDATION GATE"));
            Assert.That(logText, Does.Contain("PASS"));
        }

        [Test]
        public void ValidationGate_DetectsBrokenRecipeReference_AndHaltsPipeline()
        {
            // Verify referential integrity check logic flags broken ingredient references
            var recipesJson = File.ReadAllText("Assets/StreamingAssets/Data/recipes.json");
            Assert.That(recipesJson, Is.Not.Null);

            // JsonDataImporter.ValidateAll checks ingredient/result item IDs against itemIds HashSet
            List<string> errors = JsonDataImporter.ValidateAll();
            Assert.That(errors, Is.Not.Null);
        }
    }
}
