#!/usr/bin/env python3
"""Phase 14 (continuation) — Regenerate ASSET_REPLACEMENT_QUEUE.md
to reflect post-prioritization pending targets, post-staging structure,
and post-prompt-composition reality.

Triggered after the production manifest is built and the prompt templates
are generated. New row semantics:

  actionable rows = rows where the on-disk canonical file does not exist
                    AND the row is not Reference-Skip.
"""
import json
from pathlib import Path
from collections import Counter

REPO = Path("/home/robertsrff/Music/Atomic_War_Straving_Survival/Atomic War")
GEN = json.load(open(REPO / "docs/visual/PRODUCTION_ART_GENERATION_MANIFEST.json"))
M_OBJ = json.load(open(REPO / "docs/visual/visual_asset_manifest.json"))
MANIFEST = M_OBJ if isinstance(M_OBJ, list) else M_OBJ["active_assets"]
existing = set()
for r in MANIFEST:
    if not isinstance(r, dict): continue
    fp = r.get("full_path") or ""
    if fp.startswith("/"):
        try:
            fp = str(Path(fp).relative_to(REPO))
        except ValueError:
            pass
    if fp:
        existing.add(fp.split("/")[-1])  # basename

# Group actionable rows by family band
actionable = []
skipped = []
for row in GEN:
    if row.get("generation_status") == "SKIP_REFERENCE_ONLY":
        skipped.append(row)
        continue
    target_basename = row.get("target_filename") or f"{row['content_id']}.jpg"
    if target_basename in existing:
        # already on disk — no replacement needed
        continue
    actionable.append(row)

# Stats
band_Counter = Counter(r["runtime_priority"] for r in actionable)
fam_Counter = Counter(r["visual_family"] for r in actionable)
subfam_Counter = Counter(r["subfamily"] for r in actionable if r["visual_family"] == "Inventory-Item")

# Markdown
md = []
md.append("# ASHFALL — Visual Asset Replacement Queue (Phase 14 — Post-Prioritization)\n\n")
md.append(f"Generated by `tools/production_manifest.py` + `tools/production_ledger.py`. This is the **actionable** queue: rows whose on-disk canonical target filename doesn't exist AND that are not Reference-Skip.\n\n")
md.append(f"**Actionable rows:** {len(actionable)}\n\n")
md.append(f"**Reference-Skip rows:** {len(skipped)}\n\n")

md.append("## By priority band\n\n")
md.append("| Band | Count |\n|---|---|\n")
for b in ("P1", "P2", "P3", "P4"):
    md.append(f"| {b} | {band_Counter.get(b, 0)} |\n")
md.append(f"| **Total** | **{len(actionable)}** |\n\n")

md.append("## By family\n\n")
md.append("| Family | Count |\n|---|---|\n")
for f, n in fam_Counter.most_common():
    md.append(f"| `{f}` | {n} |\n")
md.append("\n")

md.append("## Inventory subfamily distribution\n\n")
for s, n in subfam_Counter.most_common():
    md.append(f"- `{s}`: {n}\n")
md.append("\n")

# Per-family details
md.append("## Per-family content IDs (first 60 per family)\n\n")
by_fam = {}
for r in actionable:
    by_fam.setdefault(r["visual_family"], []).append(r)

for fam, rows in sorted(by_fam.items()):
    md.append(f"### `{fam}` ({len(rows)})\n\n")
    md.append("| Content ID | Subfamily | Canonical filename | Band |\n|---|---|---|---|\n")
    for r in rows[:60]:
        md.append(f"| `{r['content_id']}` | {r['subfamily']} | `{r['target_filename']}` | {r['runtime_priority']} |\n")
    if len(rows) > 60:
        md.append(f"| … | … | … | … ({len(rows)-60} more) |\n")
    md.append("\n")

# Per prioritised source sub-catalog for locations specifically
md.append("## Source-catalog breakdown of location-art gap (200 rows)\n\n")
loc_rows = [r for r in actionable if r["visual_family"] == "Location-Art"]
loc_cats = Counter(r["source_catalog"] for r in loc_rows)
md.append("| Source catalog | Count |\n|---|---|\n")
for c, n in loc_cats.most_common():
    md.append(f"| `{c}` | {n} |\n")
md.append("\n")

out = REPO / "docs/visual/ASSET_REPLACEMENT_QUEUE.md"
out.write_text("".join(md))
print(f"→ wrote {out.name}")
print(f"actionable: {len(actionable)}; skipped (reference): {len(skipped)}")
