<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>Ashfall.UiPreview</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ui-preview.cs" />
    <ProjectReference Include="../Ashfall.Core/Ashfall.Core.csproj" />
  </ItemGroup>
</Project>
