#!/usr/bin/env python3
"""Phase 13 finance-themed utility — Re-compute wiring_matrix.md,
FALLBACK_VISUAL_ASSETS.md, ASSET_REPLACEMENT_QUEUE.md using the
postfix truth. Counts reflect Postfix resolve."""
import json
from pathlib import Path
from collections import Counter, defaultdict

REPO = Path("/home/robertsrff/Music/Atomic_War_Straving_Survival/Atomic War")

WM = json.load(open(REPO / "docs/visual/WIRING_MATRIX.json"))
CLASS = json.load(open(REPO / "docs/visual/_phase13_missing_classification.json"))

# ── WIRING_MATRIX.md ──
md = []
md.append("# ASHFALL — Visual Asset Wiring Matrix\n\n")
md.append(f"Generated by `tools/visual_wiring_postfix.py` after AssetRegistry "
          f"category-aware prefix-add normalization landed.\n\n")
md.append(f"- Total catalog-driven visual rows (deduped): **{len(WM)}**\n")
md.append(f"- Resolved: **{sum(1 for e in WM if e['resolved_path'] != 'MISSING')}**\n")
md.append(f"- Missing: **{sum(1 for e in WM if e['resolved_path'] == 'MISSING')}**\n")
md.append(f"- Resolution origin breakdown: literal=`{sum(1 for e in WM if e['resolution_origin']=='literal')}` "
          f"| semantic-alias=`{sum(1 for e in WM if e['resolution_origin']=='semantic-alias')}` "
          f"| prefix-add=`{sum(1 for e in WM if e['resolution_origin']=='prefix-add')}`\n\n")

md.append("## Wiring matrix (one row per catalog entry, deduped)\n\n")
md.append("| Content ID | Catalog | Kind | Resolved path | Origin | Status |\n")
md.append("|---|---|---|---|---|---|\n")
for e in sorted(WM, key=lambda r: (Path(r['catalog']).stem, r['content_id'])):
    status = "OK" if e['resolved_path'] != "MISSING" else "MISSING"
    rp = e['resolved_path']
    if rp == "MISSING":
        rp = "(none)"
    md.append(f"| `{e['content_id']}` | `{Path(e['catalog']).stem}` | {e['kind']} | `{rp}` | {e['resolution_origin'] or '-'} | {status} |\n")

(REPO / "docs/visual/WIRING_MATRIX.md").write_text("".join(md))
print(f"→ wrote WIRING_MATRIX.md ({sum(len(x) for x in md)} bytes)")


# ── FALLBACK_VISUAL_ASSETS.md ──
fb_rows = [e for e in WM if e['resolved_path'] == 'MISSING']
md = []
md.append("# ASHFALL — Fallback Visual Assets (Postfix)\n\n")
md.append(f"After the AssetRegistry prefix-add normalization landed, **{len(fb_rows)}** catalog-driven visual entries remain unresolved.\n\n")
md.append("These are NOT the runtime fallback texture (the production fallback texture was never triggered — verified by `--asset-registry-selftest`). They are catalog entries whose visual asset genuinely does not exist on disk.\n\n")
md.append("## Breakdown by source catalog\n\n")
mc = Counter(Path(e['catalog']).stem for e in fb_rows)
md.append("| Source catalog | Missing count |\n|---|---|\n")
for c, n in mc.most_common():
    md.append(f"| `{c}` | {n} |\n")

md.append("\n## Breakdown by classification\n\n")
md.append("| Classification | Count |\n|---|---|\n")
for cls, n in sorted(CLASS['counts'].items(), key=lambda x: -x[1]):
    md.append(f"| `{cls}` | {n} |\n")

md.append("\n## Per-row detail (first 200)\n\n")
md.append("| Content ID | Catalog | Kind | Classification |\n|---|---|---|---|\n")
def classify_of(e):
    cid = e['content_id'].lower()
    catfile = Path(e['catalog']).stem
    if catfile in {"recipes", "relic_recipes"}:
        return "F.REFERENCE_ONLY"
    if cid.startswith('ammo_deprecated_'):
        return 'E.DEPRECATED_CONTENT'
    return 'A.ACTUALLY_MISSING_ART'

for e in fb_rows[:200]:
    md.append(f"| `{e['content_id']}` | `{Path(e['catalog']).stem}` | {e['kind']} | {classify_of(e)} |\n")

(REPO / "docs/visual/FALLBACK_VISUAL_ASSETS.md").write_text("".join(md))
print(f"→ wrote FALLBACK_VISUAL_ASSETS.md")


# ── ASSET_REPLACEMENT_QUEUE.md (regenerated actually-missing only) ──
md = []
md.append("# ASHFALL — Visual Asset Replacement Queue (Postfix Truth)\n\n")
md.append(f"Generated by `tools/visual_wiring_postfix.py` + `tools/visual_wiring_classify_missing.py` after "
          f"category-aware prefix-add normalization in AssetRegistry.\n\n")
md.append(f"This queue contains only entries that the **postfix resolver** identifies as genuinely missing art. "
          f"Earlier prefix-strip/strip-cluster candidates have been reclassified; prefix-add rows have been removed "
          f"from this queue because they now resolve successfully.\n\n")
md.append(f"Total queue size: **{CLASS['counts'].get('A.ACTUALLY_MISSING_ART', 0)}** rows.\n\n")

# Group by catalog for prioritization
md.append("## Section A: ACTUALLY_MISSING_ART (real art gap)\n\n")
rowsA = []
for cls, sample_list in CLASS['samples'].items():
    if cls != "A.ACTUALLY_MISSING_ART":
        continue
    for s in sample_list:
        rowsA.append(s)

# idx-full data from WM
all_missing_a = [e for e in fb_rows if classify_of(e) == 'A.ACTUALLY_MISSING_ART']
# Per-catalog count
mc = Counter(Path(e['catalog']).stem for e in all_missing_a)
md.append("By source catalog:\n\n")
md.append("| Source | Count | Severity bucket |\n|---|---|---|\n")
for c, n in mc.most_common():
    severity = "P2" if n < 30 else "P1"
    md.append(f"| `{c}` | {n} | {severity} |\n")

md.append("\n## Group: items.json (primary item catalog)\n\n")
md.append("| Content ID | Severity | Style reference |\n|---|---|---|\n")
for e in all_missing_a[:150]:
    if Path(e['catalog']).stem != 'items':
        continue
    md.append(f"| `{e['content_id']}` | P1 | ASHFALL item icon (canonical family in `assets/art/`) |\n")

md.append("\n## Group: characters.json (NPC portrait catalog)\n\n")
md.append("| Content ID | Severity | Style reference |\n|---|---|---|\n")
for e in all_missing_a:
    if Path(e['catalog']).stem != 'characters':
        continue
    md.append(f"| `{e['content_id']}` | P1 | ASHFALL portrait (canonical family in `assets/art/`) |\n")

md.append("\n## Group: expansion sub-catalogs (year_of_ash, holdfast, crossing, verdict)\n\n")
md.append("| Content ID | Catalog |\n|---|---|\n")
for e in all_missing_a:
    s = Path(e['catalog']).stem
    if s in ('year_of_ash_items', 'year_of_ash_locations', 'holdfast_items',
             'holdfast_locations', 'crossing_items', 'crossing_locations',
             'verdict_items', 'verdict_locations', 'dose_items', 'dose_locations',
             'foundry_items', 'greenhouse_items', 'black_flotilla_items',
             'deep_lore_locations'):
        md.append(f"| `{e['content_id']}` | `{s}` |\n")

md.append("\n## Section F: REFERENCE_ONLY (no art needed — recipe action IDs)\n\n")
md.append(f"`{CLASS['counts'].get('F.REFERENCE_ONLY', 0)}` rows from `recipes.json` / `relic_recipes.json` "
          f"are recipe action IDs (e.g. `craft_bandage`, `purify_water`). These are **not** content entities — "
          f"they are game-state targets for the crafting system. No visual asset is required.\n\n")

(md_text := "".join(md))
(REPO / "docs/visual/ASSET_REPLACEMENT_QUEUE.md").write_text(md_text)
print(f"→ wrote ASSET_REPLACEMENT_QUEUE.md ({len(md_text)} bytes)")

# Summary stats
print(f"\nReplacement queue stats:")
real_art_gap = CLASS['counts'].get('A.ACTUALLY_MISSING_ART', 0)
ref_only = CLASS['counts'].get('F.REFERENCE_ONLY', 0)
print(f"  ACTUALLY_MISSING_ART (real queue): {real_art_gap}")
print(f"  REFERENCE_ONLY (do not generate): {ref_only}")
print(f"  Total trailing missing: {real_art_gap + ref_only}")
