package agentsync

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

var TargetClients = map[string]string{
	"CLAUDE.md":      "CLAUDE CODE INSTRUCTIONS — ASHFALL PROJECT",
	"CODEX.md":       "ASHFALL PROJECT — CODEX Instructions",
	"CRUSH.md":       "ASHFALL PROJECT — CRUSH Instructions",
	"GOOSE.md":       "ASHFALL PROJECT — GOOSE Instructions",
	"QWEN.md":        "ASHFALL PROJECT — QWEN Instructions",
	"VIBE.md":        "ASHFALL PROJECT — VIBE Instructions",
	"MIMOCODE.md":    "ASHFALL PROJECT — MIMOCODE Instructions",
	"OPENSETUP.md":   "ASHFALL PROJECT — OPENSETUP Instructions",
	"ANTIGRAVITY.md": "ASHFALL PROJECT — ANTIGRAVITY Instructions",
	"GEMINI.md":      "ASHFALL PROJECT — GEMINI Instructions",
	".clinerules":    "ASHFALL PROJECT — Cline Rules",
	".cursorrules":   "ASHFALL PROJECT — Cursor Rules",
	".windsurfrules": "ASHFALL PROJECT — Windsurf Rules",
}

const NonNegotiableMarker = "## READ THIS FIRST — NON-NEGOTIABLE RULES"

func SyncAgentRulebooks(repoRoot string, checkOnly bool) (bool, []string, error) {
	canonicalPath := filepath.Join(repoRoot, "AGENTS.md")
	contentBytes, err := os.ReadFile(canonicalPath)
	if err != nil {
		return false, nil, fmt.Errorf("canonical AGENTS.md not found: %w", err)
	}

	content := string(contentBytes)
	idx := strings.Index(content, NonNegotiableMarker)
	if idx == -1 {
		return false, nil, fmt.Errorf("marker %q not found in AGENTS.md", NonNegotiableMarker)
	}

	today := time.Now().UTC().Format("2006-01-02")

	var drifted []string
	var updated []string

	for filename := range TargetClients {
		targetPath := filepath.Join(repoRoot, filename)
		link, linkErr := os.Readlink(targetPath)
		existingBytes, err := os.ReadFile(targetPath)
		if linkErr != nil || link != "AGENTS.md" || err != nil || string(existingBytes) != content {
			drifted = append(drifted, filename)
			if !checkOnly {
				// Replace the entry atomically; never write through a symlink.
				temporary := targetPath + ".sync-link"
				if err := os.Symlink("AGENTS.md", temporary); err != nil {
					return false, nil, fmt.Errorf("failed to create %s: %w", temporary, err)
				}
				if err := os.Rename(temporary, targetPath); err != nil {
					_ = os.Remove(temporary)
					return false, nil, fmt.Errorf("failed to replace %s: %w", filename, err)
				}
				updated = append(updated, filename)
			}
		}
	}

	// Update report
	if !checkOnly {
		reportPath := filepath.Join(repoRoot, "docs", "agents", "AGENTS_SYNC_REPORT.md")
		_ = os.MkdirAll(filepath.Dir(reportPath), 0755)
		var report strings.Builder
		report.WriteString(fmt.Sprintf("# Agent Rulebooks Synchronization Report\nGenerated: %s\n\n", today))
		report.WriteString("All client rulebooks are relative symlinks to canonical `AGENTS.md`, generated by `ashfall-dev sync-agents`. Readers receive the complete rules through one authority:\n")
		for fn := range TargetClients {
			report.WriteString(fmt.Sprintf("- [x] `%s`\n", fn))
		}
		_ = os.WriteFile(reportPath, []byte(report.String()), 0644)
	}

	return len(drifted) == 0, updated, nil
}
